--liquibase formatted sql

--changeset dveizov:270.1
create table EXT_CORE.CF_FILE_TYP_EXTENDED
(
    FILE_TYP varchar(1) not null
        constraint CF_FILE_TYPE_EXTENDED_PK
            primary key,
    CODE varchar(255) not null,
    FILE_TYPE_NAME_EN varchar(255)
);

--changeset dveizov:270.2
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'D', 'DIVISIONAL_MARK', 'Divisional mark');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'I', 'INTERNATIONAL_MARK_I', 'International mark');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'N', 'MARK', 'Mark');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'P', 'PATENT', 'Patent');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'R', 'INTERNATIONAL_MARK_R', 'International mark');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'S', 'SPC', 'SPC');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'T', 'EPO_PATENT', 'European patent office patent');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'U', 'UTILITY_MODEL', 'Utility model');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'В', 'GEOGRAPHICAL_INDICATION_V', 'Geographical indication');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'Г', 'GEOGRAPHICAL_INDICATION', 'Geographical indication');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'Д', 'DESIGN', 'Design');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'Е', 'SINGLE_DESIGN', 'Single design');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'Н', 'INTERNATIONAL_NP', '');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'С', 'PLANTS_AND_BREEDS', 'Plants and breeds');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'У', 'INTERNATIONAL_SINGLE_DESIGN', 'International single design');
INSERT INTO EXT_CORE.CF_FILE_TYP_EXTENDED (FILE_TYP, CODE, FILE_TYPE_NAME_EN) VALUES (N'Х', 'INTERNATIONAL_DESIGN', 'International design');
