--liquibase formatted sql

--changeset dveizov:278.1
create table EXT_CORE.CF_USERDOC_TYPE
(
    USERDOC_TYP varchar(7) not null,
    PUBLIC_LIABILITIES numeric(2) not null,
    constraint EXT_CORE_CF_USERDOC_TYPE_PK
        primary key nonclustered (USERDOC_TYP)
);
INSERT INTO EXT_CORE.CF_USERDOC_TYPE (USERDOC_TYP, PUBLIC_LIABILITIES)
SELECT userdoc_typ, 1 from ipasprod.cf_userdoc_type;

UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ОАА';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ЖО';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ЖРОСП';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ЖПП';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ЖРПЛСП';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ЖРО';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ВМН';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ВОМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ОЗ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ПОДОЗ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ППЗ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ППР';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИВПИТМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ПРОМОЗ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИЗВС';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ДД';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИЗРД';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИЗРM';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИЗРПМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИОСПЗ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИОПН';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ПОМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ПОЗ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИОРМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ОМН';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИОО';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИППЛ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИПДР';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИОПЛ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИППСО';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИЧПЗМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ИЧПРМ';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'ОПО';
UPDATE EXT_CORE.CF_USERDOC_TYPE SET PUBLIC_LIABILITIES = 0 WHERE USERDOC_TYP = 'СЗ';
