alter table IPASPROD.IP_PATENT_DRAWINGS drop constraint PATENT_DRAWING_CH_FMT_DRAWING;
alter table IPASPROD.IP_PATENT_DRAWINGS
    add constraint PATENT_DRAWING_CH_FMT_DRAWING
        check ([IMAGE_FORMAT_WCODE]>=1 AND [IMAGE_FORMAT_WCODE]<=5)
alter table IPASPROD.IP_LOGO drop constraint LOGOTIPO_CH_FMT_LOGOTIPO;
alter table IPASPROD.IP_LOGO
    add constraint LOGOTIPO_CH_FMT_LOGOTIPO
        check ([IMAGE_FORMAT_WCODE]>=1 AND [IMAGE_FORMAT_WCODE]<=5);

