//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassificationTermSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClassificationTermSourceType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Rejection database"/>
 *     &lt;enumeration value="Reference database"/>
 *     &lt;enumeration value="Legacy database"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ClassificationTermSourceType")
@XmlEnum
public enum ClassificationTermSourceType {

    @XmlEnumValue("Rejection database")
    REJECTION_DATABASE("Rejection database"),
    @XmlEnumValue("Reference database")
    REFERENCE_DATABASE("Reference database"),
    @XmlEnumValue("Legacy database")
    LEGACY_DATABASE("Legacy database");
    private final String value;

    ClassificationTermSourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassificationTermSourceType fromValue(String v) {
        for (ClassificationTermSourceType c: ClassificationTermSourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
