//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchedTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchedTermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IsPartial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="MatchedClassNumber" type="{http://oami.europa.eu/trademark/goods-services/term-translation}NiceClassNumberType"/>
 *         &lt;element name="MatchedTermText" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TextType"/>
 *         &lt;element name="MatchedTermPositionInInputTermList" type="{http://oami.europa.eu/trademark/goods-services/term-translation}SubStringPositionType" minOccurs="0"/>
 *         &lt;element name="MatchedTermPositionInInputTerm" type="{http://oami.europa.eu/trademark/goods-services/term-translation}SubStringPositionType" minOccurs="0"/>
 *         &lt;element name="TargetTerm" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchedTermType", propOrder = {
    "isPartial",
    "matchedClassNumber",
    "matchedTermText",
    "matchedTermPositionInInputTermList",
    "matchedTermPositionInInputTerm",
    "targetTerm"
})
public class MatchedTermType {

    @XmlElement(name = "IsPartial")
    protected Boolean isPartial;
    @XmlElement(name = "MatchedClassNumber")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int matchedClassNumber;
    @XmlElement(name = "MatchedTermText", required = true)
    protected TextType matchedTermText;
    @XmlElement(name = "MatchedTermPositionInInputTermList")
    protected SubStringPositionType matchedTermPositionInInputTermList;
    @XmlElement(name = "MatchedTermPositionInInputTerm")
    protected SubStringPositionType matchedTermPositionInInputTerm;
    @XmlElement(name = "TargetTerm")
    protected String targetTerm;

    /**
     * Gets the value of the isPartial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPartial() {
        return isPartial;
    }

    /**
     * Sets the value of the isPartial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPartial(Boolean value) {
        this.isPartial = value;
    }

    /**
     * Gets the value of the matchedClassNumber property.
     * 
     */
    public int getMatchedClassNumber() {
        return matchedClassNumber;
    }

    /**
     * Sets the value of the matchedClassNumber property.
     * 
     */
    public void setMatchedClassNumber(int value) {
        this.matchedClassNumber = value;
    }

    /**
     * Gets the value of the matchedTermText property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getMatchedTermText() {
        return matchedTermText;
    }

    /**
     * Sets the value of the matchedTermText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setMatchedTermText(TextType value) {
        this.matchedTermText = value;
    }

    /**
     * Gets the value of the matchedTermPositionInInputTermList property.
     * 
     * @return
     *     possible object is
     *     {@link SubStringPositionType }
     *     
     */
    public SubStringPositionType getMatchedTermPositionInInputTermList() {
        return matchedTermPositionInInputTermList;
    }

    /**
     * Sets the value of the matchedTermPositionInInputTermList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubStringPositionType }
     *     
     */
    public void setMatchedTermPositionInInputTermList(SubStringPositionType value) {
        this.matchedTermPositionInInputTermList = value;
    }

    /**
     * Gets the value of the matchedTermPositionInInputTerm property.
     * 
     * @return
     *     possible object is
     *     {@link SubStringPositionType }
     *     
     */
    public SubStringPositionType getMatchedTermPositionInInputTerm() {
        return matchedTermPositionInInputTerm;
    }

    /**
     * Sets the value of the matchedTermPositionInInputTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubStringPositionType }
     *     
     */
    public void setMatchedTermPositionInInputTerm(SubStringPositionType value) {
        this.matchedTermPositionInInputTerm = value;
    }

    /**
     * Gets the value of the targetTerm property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetTerm() {
        return targetTerm;
    }

    /**
     * Sets the value of the targetTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetTerm(String value) {
        this.targetTerm = value;
    }

}
