//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://oami.europa.eu/trademark/goods-services/term-translation", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.duosoft.ipas.integration.tmclass.translate.model;
