//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermTranslationRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TermTranslationRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassificationTermText" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TextType"/>
 *         &lt;element name="TargetLanguageCode" type="{http://oami.europa.eu/trademark/goods-services/term-translation}EM_ApplicationLanguageCodeType"/>
 *         &lt;element name="ClassNumber" type="{http://oami.europa.eu/trademark/goods-services/term-translation}NiceClassNumberType" minOccurs="0"/>
 *         &lt;element name="SearchOnSublevel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TermTranslationRequestType", propOrder = {
    "classificationTermText",
    "targetLanguageCode",
    "classNumber",
    "searchOnSublevel"
})
public class TermTranslationRequestType {

    @XmlElement(name = "ClassificationTermText", required = true)
    protected TextType classificationTermText;
    @XmlElement(name = "TargetLanguageCode", required = true)
    @XmlSchemaType(name = "NMTOKEN")
    protected EMApplicationLanguageCodeType targetLanguageCode;
    @XmlElement(name = "ClassNumber")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer classNumber;
    @XmlElement(name = "SearchOnSublevel")
    protected Boolean searchOnSublevel;

    /**
     * Gets the value of the classificationTermText property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getClassificationTermText() {
        return classificationTermText;
    }

    /**
     * Sets the value of the classificationTermText property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setClassificationTermText(TextType value) {
        this.classificationTermText = value;
    }

    /**
     * Gets the value of the targetLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link EMApplicationLanguageCodeType }
     *     
     */
    public EMApplicationLanguageCodeType getTargetLanguageCode() {
        return targetLanguageCode;
    }

    /**
     * Sets the value of the targetLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMApplicationLanguageCodeType }
     *     
     */
    public void setTargetLanguageCode(EMApplicationLanguageCodeType value) {
        this.targetLanguageCode = value;
    }

    /**
     * Gets the value of the classNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassNumber() {
        return classNumber;
    }

    /**
     * Sets the value of the classNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassNumber(Integer value) {
        this.classNumber = value;
    }

    /**
     * Gets the value of the searchOnSublevel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchOnSublevel() {
        return searchOnSublevel;
    }

    /**
     * Sets the value of the searchOnSublevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchOnSublevel(Boolean value) {
        this.searchOnSublevel = value;
    }

}
