//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TermTranslationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TermTranslationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TermTranslationRequest" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TermTranslationRequestType"/>
 *         &lt;element name="TermTranslationResponseDetails" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TermTranslationResponseDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TermTranslationType", propOrder = {
    "termTranslationRequest",
    "termTranslationResponseDetails"
})
public class TermTranslationType {

    @XmlElement(name = "TermTranslationRequest", required = true)
    protected TermTranslationRequestType termTranslationRequest;
    @XmlElement(name = "TermTranslationResponseDetails", required = true)
    protected TermTranslationResponseDetailsType termTranslationResponseDetails;

    /**
     * Gets the value of the termTranslationRequest property.
     * 
     * @return
     *     possible object is
     *     {@link TermTranslationRequestType }
     *     
     */
    public TermTranslationRequestType getTermTranslationRequest() {
        return termTranslationRequest;
    }

    /**
     * Sets the value of the termTranslationRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermTranslationRequestType }
     *     
     */
    public void setTermTranslationRequest(TermTranslationRequestType value) {
        this.termTranslationRequest = value;
    }

    /**
     * Gets the value of the termTranslationResponseDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TermTranslationResponseDetailsType }
     *     
     */
    public TermTranslationResponseDetailsType getTermTranslationResponseDetails() {
        return termTranslationResponseDetails;
    }

    /**
     * Sets the value of the termTranslationResponseDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermTranslationResponseDetailsType }
     *     
     */
    public void setTermTranslationResponseDetails(TermTranslationResponseDetailsType value) {
        this.termTranslationResponseDetails = value;
    }

}
