//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionBody" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TransactionBodyType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionType", propOrder = {
    "transactionBody"
})
public class TransactionType {

    @XmlElement(name = "TransactionBody", required = true)
    protected TransactionBodyType transactionBody;

    /**
     * Gets the value of the transactionBody property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionBodyType }
     *     
     */
    public TransactionBodyType getTransactionBody() {
        return transactionBody;
    }

    /**
     * Sets the value of the transactionBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionBodyType }
     *     
     */
    public void setTransactionBody(TransactionBodyType value) {
        this.transactionBody = value;
    }

}
