//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TermTranslation" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TermTranslationType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDataType", propOrder = {
    "termTranslation"
})
public class TransactionDataType {

    @XmlElement(name = "TermTranslation", required = true)
    protected TermTranslationType termTranslation;

    /**
     * Gets the value of the termTranslation property.
     * 
     * @return
     *     possible object is
     *     {@link TermTranslationType }
     *     
     */
    public TermTranslationType getTermTranslation() {
        return termTranslation;
    }

    /**
     * Sets the value of the termTranslation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TermTranslationType }
     *     
     */
    public void setTermTranslation(TermTranslationType value) {
        this.termTranslation = value;
    }

}
