//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TranslationResultType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TranslationResultType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="OK"/>
 *     &lt;enumeration value="Hint"/>
 *     &lt;enumeration value="Not OK"/>
 *     &lt;enumeration value="None"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TranslationResultType")
@XmlEnum
public enum TranslationResultType {

    OK("OK"),
    @XmlEnumValue("Hint")
    HINT("Hint"),
    @XmlEnumValue("Not OK")
    NOT_OK("Not OK"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    TranslationResultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TranslationResultType fromValue(String v) {
        for (TranslationResultType c: TranslationResultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
