//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.03.04 at 11:05:36 AM EET 
//


package bg.duosoft.ipas.integration.tmclass.translate.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TranslatedTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TranslatedTermType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MatchingTerm" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TextType"/>
 *         &lt;element name="MatchingTermPositionInInputTermList" type="{http://oami.europa.eu/trademark/goods-services/term-translation}SubStringPositionType"/>
 *         &lt;element name="MatchedTerms" type="{http://oami.europa.eu/trademark/goods-services/term-translation}MatchedTermsType" minOccurs="0"/>
 *         &lt;element name="TranslationAssessment" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TranslationAssessmentType"/>
 *         &lt;element name="TranslationResult" type="{http://oami.europa.eu/trademark/goods-services/term-translation}TranslationResultType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TranslatedTermType", propOrder = {
    "matchingTerm",
    "matchingTermPositionInInputTermList",
    "matchedTerms",
    "translationAssessment",
    "translationResult"
})
public class TranslatedTermType {

    @XmlElement(name = "MatchingTerm", required = true)
    protected TextType matchingTerm;
    @XmlElement(name = "MatchingTermPositionInInputTermList", required = true)
    protected SubStringPositionType matchingTermPositionInInputTermList;
    @XmlElement(name = "MatchedTerms")
    protected MatchedTermsType matchedTerms;
    @XmlElement(name = "TranslationAssessment", required = true)
    @XmlSchemaType(name = "token")
    protected TranslationAssessmentType translationAssessment;
    @XmlElement(name = "TranslationResult", required = true)
    @XmlSchemaType(name = "token")
    protected TranslationResultType translationResult;

    /**
     * Gets the value of the matchingTerm property.
     * 
     * @return
     *     possible object is
     *     {@link TextType }
     *     
     */
    public TextType getMatchingTerm() {
        return matchingTerm;
    }

    /**
     * Sets the value of the matchingTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link TextType }
     *     
     */
    public void setMatchingTerm(TextType value) {
        this.matchingTerm = value;
    }

    /**
     * Gets the value of the matchingTermPositionInInputTermList property.
     * 
     * @return
     *     possible object is
     *     {@link SubStringPositionType }
     *     
     */
    public SubStringPositionType getMatchingTermPositionInInputTermList() {
        return matchingTermPositionInInputTermList;
    }

    /**
     * Sets the value of the matchingTermPositionInInputTermList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubStringPositionType }
     *     
     */
    public void setMatchingTermPositionInInputTermList(SubStringPositionType value) {
        this.matchingTermPositionInInputTermList = value;
    }

    /**
     * Gets the value of the matchedTerms property.
     * 
     * @return
     *     possible object is
     *     {@link MatchedTermsType }
     *     
     */
    public MatchedTermsType getMatchedTerms() {
        return matchedTerms;
    }

    /**
     * Sets the value of the matchedTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchedTermsType }
     *     
     */
    public void setMatchedTerms(MatchedTermsType value) {
        this.matchedTerms = value;
    }

    /**
     * Gets the value of the translationAssessment property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationAssessmentType }
     *     
     */
    public TranslationAssessmentType getTranslationAssessment() {
        return translationAssessment;
    }

    /**
     * Sets the value of the translationAssessment property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationAssessmentType }
     *     
     */
    public void setTranslationAssessment(TranslationAssessmentType value) {
        this.translationAssessment = value;
    }

    /**
     * Gets the value of the translationResult property.
     * 
     * @return
     *     possible object is
     *     {@link TranslationResultType }
     *     
     */
    public TranslationResultType getTranslationResult() {
        return translationResult;
    }

    /**
     * Sets the value of the translationResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link TranslationResultType }
     *     
     */
    public void setTranslationResult(TranslationResultType value) {
        this.translationResult = value;
    }

}
