--liquibase formatted sql

--changeset dveizov:240.1
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT ADD ABDOCS_DOCUMENT_ID_SHA_256_HEX varchar(64);

--changeset dveizov:240.3
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT ADD MAIL_READ_DATE DATETIME;

--changeset dveizov:240.2
UPDATE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT SET ABDOCS_DOCUMENT_ID_SHA_256_HEX = (SELECT LOWER(CONVERT(varchar(max), HASHBYTES('SHA2_256', CAST(ABDOCS_DOCUMENT_ID as varchar)),2))) where ABDOCS_DOCUMENT_ID IS NOT NULL


