--liquibase formatted sql

--changeset dveizov:243.1
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT DROP COLUMN MAIL_READ_DATE;

--changeset dveizov:243.2
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT ADD EMAIL_NOTIFICATION_READ_DATE DATETIME;

--changeset dveizov:243.3
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT ADD PORTAL_NOTIFICATION_READ_DATE DATETIME;

