--liquibase formatted sql

--changeset dveizov:244.1
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('IP_OFFIDOC_ABDOCS_ID_HASH_SALT', 'IPAS2020');

--changeset dveizov:244.2
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT DROP COLUMN ABDOCS_DOCUMENT_ID_SHA_256_HEX ;

--changeset dveizov:244.3
ALTER TABLE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT ADD ABDOCS_DOCUMENT_ID_SHA256_SALTED_HEX varchar(64);

--changeset dveizov:244.4
UPDATE EXT_CORE.IP_OFFIDOC_ABDOCS_DOCUMENT SET ABDOCS_DOCUMENT_ID_SHA256_SALTED_HEX = (SELECT LOWER(CONVERT(varchar(max), HASHBYTES('SHA2_256', (SELECT CONCAT(CAST(ABDOCS_DOCUMENT_ID as varchar), (SELECT p.VALUE FROM IPASPROD.EXT_CONFIG_PARAM p where p.CONFIG_CODE = 'IP_OFFIDOC_ABDOCS_ID_HASH_SALT' )))),2))) where ABDOCS_DOCUMENT_ID IS NOT NULL;


