--liquibase formatted sql

--changeset mmurlev:240.1
ALTER TABLE EXT_CORE.IP_PATENT_ATTACHMENTS
ADD PUBLISH_DRAWING_DATA IMAGE;

--changeset mmurlev:240.2
ALTER TABLE EXT_CORE.IP_PATENT_ATTACHMENTS
ADD PUBLISH_CLAIM_DATA IMAGE;

--changeset mmurlev:240.3
ALTER TABLE EXT_CORE.IP_PATENT_ATTACHMENTS
ADD PUBLISH_DESCRIPTION_DATA IMAGE;

--changeset mmurlev:240.4
ALTER TABLE EXT_CORE.IP_PATENT_ATTACHMENTS
ADD PUBLISH_DRAWING_FILE_NAME VARCHAR(255);

--changeset mmurlev:240.5
ALTER TABLE EXT_CORE.IP_PATENT_ATTACHMENTS
ADD PUBLISH_CLAIM_FILE_NAME VARCHAR(255);

--changeset mmurlev:240.6
ALTER TABLE EXT_CORE.IP_PATENT_ATTACHMENTS
ADD PUBLISH_DESCRIPTION_FILE_NAME VARCHAR(255);