--liquibase formatted sql

--changeset mmurlev:250.1
create table EXT_CORE.CF_ATTACHMENT_TYPE
(
    id int not null primary key,
    name varchar(100)
);

--changeset mmurlev:250.2
insert into ext_core.CF_ATTACHMENT_TYPE (id, name) values (1,'Описание')
insert into ext_core.CF_ATTACHMENT_TYPE (id, name) values (2,'Чертежи')
insert into ext_core.CF_ATTACHMENT_TYPE (id, name) values (3,'Претенции')
insert into ext_core.CF_ATTACHMENT_TYPE (id, name) values (4,'Описание за публикация')
insert into ext_core.CF_ATTACHMENT_TYPE (id, name) values (5,'Чертежи за публикация')
insert into ext_core.CF_ATTACHMENT_TYPE (id, name) values (6,'Претенции за публикация')

--changeset mmurlev:250.3
CREATE TABLE EXT_CORE.IP_PATENT_DETAILS
(
    FILE_SEQ VARCHAR(2) NOT NULL,
    FILE_TYP VARCHAR(1) NOT NULL,
    FILE_SER NUMERIC(4) NOT NULL,
    FILE_NBR NUMERIC(10) NOT NULL,
    DRAWINGS NUMERIC(10),
    DRAWING_PUBLICATIONS NUMERIC(10),
    DESCRIPTION_PAGES NUMERIC(10),
    INVENTIONS_GROUP  NUMERIC(10),
    CLAIMS NUMERIC(10),
    CONSTRAINT IP_PATENT_DETAILS_PK PRIMARY KEY (FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER)
)

--changeset mmurlev:250.4
CREATE TABLE EXT_CORE.IP_PATENT_ATTACHMENT
(
    ID integer not null,
    FILE_SEQ VARCHAR(2) NOT NULL,
    FILE_TYP VARCHAR(1) NOT NULL,
    FILE_SER NUMERIC(4) NOT NULL,
    FILE_NBR NUMERIC(10) NOT NULL,
    ATTACHMENT_TYPE_ID int not null references EXT_CORE.CF_ATTACHMENT_TYPE(id) ,
    ATTACHMENT_CONTENT varbinary(max),
    ATTACHMENT_NAME VARCHAR(255),
    DATE_CREATED datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    CONSTRAINT IP_PATENT_ATTACHMENT_PK PRIMARY KEY (ID,FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER,ATTACHMENT_TYPE_ID)
)

--changeset mmurlev:250.5
INSERT INTO EXT_CORE.IP_PATENT_DETAILS (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, DRAWINGS, DRAWING_PUBLICATIONS, DESCRIPTION_PAGES, INVENTIONS_GROUP, CLAIMS)
SELECT FILE_SEQ,FILE_TYP,FILE_SER,FILE_NBR,DRAWINGS_CNT,DRAWING_PUBL,DESCRIPTION_PAGES_CNT,INVENTIONS_GROUP_CNT,CLAIMS_CNT FROM EXT_CORE.IP_PATENT_ATTACHMENTS

--changeset mmurlev:250.6
INSERT INTO EXT_CORE.IP_PATENT_ATTACHMENT (ID, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, ATTACHMENT_TYPE_ID, ATTACHMENT_CONTENT, ATTACHMENT_NAME,DATE_CREATED)
SELECT 1,at.FILE_SEQ,at.FILE_TYP,at.FILE_SER,at.FILE_NBR,2,at.DRAWING_DATA,at.DRAWING_FILE_NAME,f.FILING_DATE FROM EXT_CORE.IP_PATENT_ATTACHMENTS at
inner join IP_FILE f on f.FILE_NBR = at.FILE_NBR and f.FILE_TYP = at.FILE_TYP and f.FILE_SER = at.FILE_SER and f.FILE_SEQ = at.FILE_SEQ
WHERE at.DRAWING_DATA IS NOT NULL

--changeset mmurlev:250.7
INSERT INTO EXT_CORE.IP_PATENT_ATTACHMENT (ID, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, ATTACHMENT_TYPE_ID, ATTACHMENT_CONTENT, ATTACHMENT_NAME,DATE_CREATED)
SELECT 1,at.FILE_SEQ,at.FILE_TYP,at.FILE_SER,at.FILE_NBR,1,at.DESCRIPTION_DATA,at.DESCRIPTION_FILE_NAME,f.FILING_DATE FROM EXT_CORE.IP_PATENT_ATTACHMENTS at
inner join IP_FILE f on f.FILE_NBR = at.FILE_NBR and f.FILE_TYP = at.FILE_TYP and f.FILE_SER = at.FILE_SER and f.FILE_SEQ = at.FILE_SEQ
WHERE at.DESCRIPTION_DATA IS NOT NULL

--changeset mmurlev:250.8
INSERT INTO EXT_CORE.IP_PATENT_ATTACHMENT (ID, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, ATTACHMENT_TYPE_ID, ATTACHMENT_CONTENT, ATTACHMENT_NAME,DATE_CREATED)
SELECT 1,at.FILE_SEQ,at.FILE_TYP,at.FILE_SER,at.FILE_NBR,3,at.CLAIM_DATA,at.CLAIM_FILE_NAME,f.FILING_DATE FROM EXT_CORE.IP_PATENT_ATTACHMENTS at
inner join IP_FILE f on f.FILE_NBR = at.FILE_NBR and f.FILE_TYP = at.FILE_TYP and f.FILE_SER = at.FILE_SER and f.FILE_SEQ = at.FILE_SEQ
WHERE at.CLAIM_DATA IS NOT NULL

--changeset mmurlev:250.9
INSERT INTO EXT_CORE.IP_PATENT_ATTACHMENT (ID, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, ATTACHMENT_TYPE_ID, ATTACHMENT_CONTENT, ATTACHMENT_NAME,DATE_CREATED)
SELECT 1,at.FILE_SEQ,at.FILE_TYP,at.FILE_SER,at.FILE_NBR,4,at.PUBLISH_DESCRIPTION_DATA,at.PUBLISH_DESCRIPTION_FILE_NAME,f.FILING_DATE FROM EXT_CORE.IP_PATENT_ATTACHMENTS at
inner join IP_FILE f on f.FILE_NBR = at.FILE_NBR and f.FILE_TYP = at.FILE_TYP and f.FILE_SER = at.FILE_SER and f.FILE_SEQ = at.FILE_SEQ
WHERE at.PUBLISH_DESCRIPTION_DATA IS NOT NULL

--changeset mmurlev:250.10
INSERT INTO EXT_CORE.IP_PATENT_ATTACHMENT (ID, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, ATTACHMENT_TYPE_ID, ATTACHMENT_CONTENT, ATTACHMENT_NAME,DATE_CREATED)
SELECT 1,at.FILE_SEQ,at.FILE_TYP,at.FILE_SER,at.FILE_NBR,5,at.PUBLISH_DRAWING_DATA,at.PUBLISH_DRAWING_FILE_NAME,f.FILING_DATE FROM EXT_CORE.IP_PATENT_ATTACHMENTS at
inner join IP_FILE f on f.FILE_NBR = at.FILE_NBR and f.FILE_TYP = at.FILE_TYP and f.FILE_SER = at.FILE_SER and f.FILE_SEQ = at.FILE_SEQ
WHERE at.PUBLISH_DRAWING_DATA IS NOT NULL

--changeset mmurlev:250.11
INSERT INTO EXT_CORE.IP_PATENT_ATTACHMENT (ID, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, ATTACHMENT_TYPE_ID, ATTACHMENT_CONTENT, ATTACHMENT_NAME,DATE_CREATED)
SELECT 1,at.FILE_SEQ,at.FILE_TYP,at.FILE_SER,at.FILE_NBR,6,at.PUBLISH_CLAIM_DATA,at.PUBLISH_CLAIM_FILE_NAME,f.FILING_DATE FROM EXT_CORE.IP_PATENT_ATTACHMENTS at
inner join IP_FILE f on f.FILE_NBR = at.FILE_NBR and f.FILE_TYP = at.FILE_TYP and f.FILE_SER = at.FILE_SER and f.FILE_SEQ = at.FILE_SEQ
WHERE at.PUBLISH_CLAIM_DATA IS NOT NULL