--liquibase formatted sql

--changeset dveizov:254.1
UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 60),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Фани Божинова', 'Фани Владимирова Божинова')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;


UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 17),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Марио Христов', 'Марио Николов Христов')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 25),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Валентина Нешева', 'Валентина Великова Нешева')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 198),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Вася Германова', 'Вася Иванова Германова')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 245),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Елена Божинова-Милър', 'Елена Милър')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 461),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Момчил Златарев', 'Момчил Йорданов Златарев')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 202),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Иван Иванов', 'Иван Николов Иванов')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 87),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in
      ('Мария ЯНАКИЕВА-ЗЛАТАРЕВА', 'Мария Николова Янакиева-Златарева', 'Maрия Николова Янакиева Златарева',
       'Maрия Николова Янакиева-Златарева', 'Maрия Янакиева-Златарева')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 303),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Офелия Киркорян-Цонкова')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 581),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME in ('Силвия Тодорова', 'Силвия Христова Тодорова')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'PA',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM EXT_AGENT.EXTENDED_PARTNERSHIP a where a.PARTNERSHIP_CODE = 'A2'),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME like '%IP Consulting%'
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'PA',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM EXT_AGENT.EXTENDED_PARTNERSHIP a where a.PARTNERSHIP_CODE = 'A1'),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME like '%петош%'
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 100),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME IN ('Д-р инж Павко Иларионов', 'Д-р Павко Иларионов')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 94),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME IN ('Ани Тинева Максимова')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 197),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME IN ('Теодора Георгиева-Дачева')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 242),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME IN ('Теодора Валентинова Ценова')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = (SELECT a.PERSON_NBR FROM IPASPROD.IP_PERSON a where a.AGENT_CODE = 3),
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
WHERE p.PERSON_NAME IN ('ЕМИЛ ГАБРИЕЛ БЕНАТОВ')
  and d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  AND d.REPRESENTATIVE_TYP IS NULL;

UPDATE d
SET d.REPRESENTATIVE_TYP = 'AG',
    d.PERSON_NBR         = agp.PERSON_NBR,
    d.ADDR_NBR           = 1
FROM EXT_CORE.IP_USERDOC_PERSON d
         JOIN IPASPROD.IP_PERSON p on d.PERSON_NBR = p.PERSON_NBR
         JOIN IPASPROD.IP_AGENT a
              on ((p.PERSON_NAME = a.AGENT_NAME) OR
                  (p.PERSON_NAME in ((CONCAT(left(a.AGENT_NAME, charindex(' ', a.AGENT_NAME + ' ') - 1), ' ',
                                             right(a.AGENT_NAME, charindex(' ', reverse(a.AGENT_NAME) + ' ') - 1))))))
         join IPASPROD.IP_PERSON agp on a.AGENT_CODE = agp.AGENT_CODE
WHERE p.AGENT_CODE is null
  AND d.REPRESENTATIVE_TYP IS NULL
  AND d.ROLE IN ('REPRESENTATIVE', 'OLD_REPRESENTATIVE', 'NEW_REPRESENTATIVE')
  and a.AGENT_CODE < 10000;