--liquibase formatted sql

--changeset ggeorgiev:252.1
CREATE INDEX [IP_FILE_OWNER_CHANGES_PERSON_NBR_INDEX] ON [IPASPROD].[IP_FILE_OWNER_CHANGES] ([PERSON_NBR] ASC);

--changeset ggeorgiev:252.2
EXEC sp_rename '[IPASPROD].[IP_FILE_OWNER_CHANGES]', 'IP_FILE_PERSON_CHANGES';
ALTER TABLE IPASPROD.IP_FILE_PERSON_CHANGES ADD PERSON_TYPE varchar(2);
UPDATE IPASPROD.IP_FILE_PERSON_CHANGES set PERSON_TYPE = 'O' where 1 = 1;
ALTER TABLE IPASPROD.IP_FILE_PERSON_CHANGES alter column PERSON_TYPE varchar(2) NOT NULL;

--changeset ggeorgiev:252.3
drop trigger IPASPROD.[FILE_OWNER_CHANGES];
drop trigger IPASPROD.[MARK_OWNER_CHANGES];
drop trigger IPASPROD.[PATENT_OWNER_CHANGES];
drop trigger IPASPROD.[FILE_OWNER_ADDRESS_CHANGES];

--changeset ggeorgiev:252.4 splitStatements:false
CREATE TRIGGER IPASPROD.[FILE_PERSON_CHANGES]
    ON IPASPROD.IP_PERSON
    AFTER UPDATE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, i.PERSON_NBR, GETDATE(), 'O'
    FROM inserted i
         join IPASPROD.VW_FILE_OWNERS o on o.PERSON_NBR = i.PERSON_NBR;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, i.PERSON_NBR, GETDATE(), 'R'
    FROM inserted i
         join IPASPROD.VW_FILE_REPRS o on o.PERSON_NBR = i.PERSON_NBR;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, i.PERSON_NBR, GETDATE(), 'I'
    FROM inserted i
         join IPASPROD.IP_PATENT_INVENTORS o on o.PERSON_NBR = i.PERSON_NBR;

END;

ALTER TABLE IPASPROD.IP_PERSON ENABLE TRIGGER FILE_PERSON_CHANGES;



--changeset ggeorgiev:252.5 splitStatements:false

CREATE TRIGGER IPASPROD.[FILE_PERSON_ADDRESS_CHANGES]
    ON IPASPROD.IP_PERSON_ADDRESSES
    AFTER UPDATE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, i.PERSON_NBR, i.ADDR_NBR, GETDATE(), 'O'
    FROM inserted i JOIN IPASPROD.VW_FILE_OWNERS o on o.PERSON_NBR = i.PERSON_NBR and o.ADDR_NBR = i.ADDR_NBR;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, i.PERSON_NBR, i.ADDR_NBR, GETDATE(), 'R'
    FROM inserted i JOIN IPASPROD.VW_FILE_REPRS o on o.PERSON_NBR = i.PERSON_NBR and o.ADDR_NBR = i.ADDR_NBR;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, i.PERSON_NBR, i.ADDR_NBR, GETDATE(), 'I'
    FROM inserted i JOIN IPASPROD.VW_FILE_REPRS o on o.PERSON_NBR = i.PERSON_NBR and o.ADDR_NBR = i.ADDR_NBR;

END;

ALTER TABLE IPASPROD.IP_PERSON_ADDRESSES ENABLE TRIGGER FILE_PERSON_ADDRESS_CHANGES;

--ideata na dolnite triggers e che koda za obedinqvane/razdelqna na persons promenq tablicite IP_MARK(PATENT)_OWNERS/REPRS i trqbva da ima trigger, kojto da pishe v IP_FILE_PERSON_CHANGES pri promqna v mark/patent/owners/reprs
--changeset ggeorgiev:252.6 splitStatements:false

CREATE TRIGGER IPASPROD.[MARK_OWNER_CHANGES]
    ON IPASPROD.IP_MARK_OWNERS
    AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'O'
    FROM inserted i;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'O'
    FROM deleted d;

END;

ALTER TABLE IPASPROD.IP_MARK_OWNERS ENABLE TRIGGER MARK_OWNER_CHANGES;

--changeset ggeorgiev:252.7 splitStatements:false

CREATE TRIGGER IPASPROD.[MARK_REPRS_CHANGES]
    ON IPASPROD.IP_MARK_REPRS
    AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'R'
    FROM inserted i;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'R'
    FROM deleted d;
END;

ALTER TABLE IPASPROD.IP_MARK_REPRS ENABLE TRIGGER MARK_REPRS_CHANGES;

--changeset ggeorgiev:252.8 splitStatements:false

CREATE TRIGGER IPASPROD.[PATENT_OWNER_CHANGES]
    ON IPASPROD.IP_PATENT_OWNERS
    AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'O'
    FROM inserted i;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'O'
    FROM deleted d;
END;

ALTER TABLE IPASPROD.IP_PATENT_OWNERS ENABLE TRIGGER PATENT_OWNER_CHANGES;

--changeset ggeorgiev:252.9 splitStatements:false

CREATE TRIGGER IPASPROD.[PATENT_REPRS_CHANGES]
    ON IPASPROD.IP_PATENT_REPRS
    AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'R'
    FROM inserted i;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'R'
    FROM deleted d;
END;

ALTER TABLE IPASPROD.IP_PATENT_REPRS ENABLE TRIGGER PATENT_REPRS_CHANGES;

--changeset ggeorgiev:252.10 splitStatements:false

CREATE TRIGGER IPASPROD.[PATENT_INVENTORS_CHANGES]
    ON IPASPROD.IP_PATENT_INVENTORS
    AFTER INSERT, UPDATE, DELETE
    AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'I'
    FROM inserted i;

    INSERT INTO IPASPROD.IP_FILE_PERSON_CHANGES (FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, DATE_CHANGED, PERSON_TYPE)
    SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR, GETDATE(), 'I'
    FROM deleted d;
END;

ALTER TABLE IPASPROD.IP_PATENT_INVENTORS ENABLE TRIGGER PATENT_INVENTORS_CHANGES;