--liquibase formatted sql

--changeset dveizov:259.1
CREATE TABLE EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC
(
    RECEPTION_TYPE numeric(18) not null,
    USERDOC_TYPE   varchar(7)  not null,
    SEQ_NBR        numeric(6)  not null,
    constraint RECEPTION_TYPE_ADDITIONAL_USERDOC_PK
        primary key (RECEPTION_TYPE, USERDOC_TYPE)
);

--changeset dveizov:259.2
alter table EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC
    add constraint RECEPTION_ADDITIONAL_USERDOC_CF_RECEPTION_TYPE__ID_fk
        foreign key (RECEPTION_TYPE) references EXT_RECEPTION.CF_RECEPTION_TYPE (ID);

--changeset dveizov:259.3
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (2, 'ППЛН',1); --Пълномощно
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (2, 'ПЛТ',2); -- Документ за платена такса
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (2, 'ДПр',3); -- Декларация за приоритет (само за патенти и полезни модели)
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (2, 'ДММП',4); -- Декларация за МСП, Висше училище или изобретател (само за патенти и полезни модели)
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (2, 'ДЛГ',5); --Декларация за лицензионна готовност (само за патенти и полезни модели)
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (2, 'ИУП',6); --Искане за ускорена публикация (само за патент)

INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (4, 'ППЛН',1); --Пълномощно
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (4, 'ПЛТ',2); -- Документ за платена такса
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (4, 'ДПр',3); -- Декларация за приоритет (само за патенти и полезни модели)
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (4, 'ДММП',4); -- Декларация за МСП, Висше училище или изобретател (само за патенти и полезни модели)
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (4, 'ДЛГ',5); --Декларация за лицензионна готовност (само за патенти и полезни модели)
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (4, 'МОРПМ',6); --Искане за отложена регистрация (само за полезен модел)

INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (8, 'ППЛН',1); --Пълномощно
INSERT INTO EXT_RECEPTION.RECEPTION_TYPE_ADDITIONAL_USERDOC (RECEPTION_TYPE, USERDOC_TYPE,SEQ_NBR) VALUES (8, 'ПЛТ',2); -- Документ за платена такса



