package bg.duosoft.ipas.core.service.nomenclature;

import bg.duosoft.ipas.core.model.CConfigParam;

public interface ConfigParamService {
    String EXCLUDED_RESPONSIBLE_USERS = "EXCLUDED_RESPONSIBLE_USERS";
    String EXT_CONFIG_PARAM_EPO_PATENT_VALIDATION_ACTION_TYPE = "EPO_PATENT_VALIDATION_ACTION_TYPE";
    String EXT_CONFIG_PARAM_EPO_PATENT_VALIDATION_STATUS_CODE = "EPO_PATENT_VALIDATION_STATUS_CODE";
    String OFFICE_DOCUMENT_TEMPLATES_DIRECTORY = "DirectorioOficios";
    String REPORT_DOCUMENT_TEMPLATES_DIRECTORY = "DirectorioReportesWord";
    String ABODCS_USER_TO_WHOM_DOCUMENT_IS_SEND_ON_REGISTRATION = "ABODCS_USER_TO_WHOM_DOCUMENT_IS_SEND_ON_REGISTRATION";
    String IP_OFFIDOC_ABDOCS_ID_HASH_SALT = "IP_OFFIDOC_ABDOCS_ID_HASH_SALT";
    String EXPIRING_MARK_NOTIFICATION_TEMPLATE = "EXPIRING_MARK_NOTIFICATION_TEMPLATE";
    String EXPIRING_MARK_NOTIFICATION_ABDOCS_DOCUMENT_TO = "EXPIRING_MARK_NOTIFICATION_ABDOCS_DOCUMENT_TO";
    String PATENT_CERTIFICATE_PAID_FEES_TEMPLATE = "PATENT_CERTIFICATE_PAID_FEES_TEMPLATE";
    String ABDOCS_NOTE_FOR_USER_TARGETING_ON_RESPONSIBLE_USER_CHANGE = "ABDOCS_NOTE_FOR_USER_TARGETING_ON_RESPONSIBLE_USER_CHANGE";
    String EXT_CONFIG_PARAM_INTL_MARK_SURRENDER_PROTECTION_ACTION_TYPE = "INTL_MARK_SURRENDER_PROTECTION_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_SURRENDER_PROTECTION_STATUS_CODE = "INTL_MARK_SURRENDER_PROTECTION_STATUS_CODE";
    String EXT_CONFIG_PARAM_INTL_MARK_CANCELLATION_ACTION_TYPE = "INTL_MARK_CANCELLATION_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_CANCELLATION_STATUS_CODE = "INTL_MARK_CANCELLATION_STATUS_CODE";
    String EXT_CONFIG_PARAM_INTL_MARK_NON_RENEWAL_OF_TRADEMARK_ACTION_TYPE = "INTL_MARK_NON_RENEWAL_OF_TRADEMARK_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_NON_RENEWAL_OF_TRADEMARK_STATUS_CODE = "INTL_MARK_NON_RENEWAL_OF_TRADEMARK_STATUS_CODE";
    String EXT_CONFIG_PARAM_INTL_MARK_NON_RENEWAL_OF_CONTRACTING_PARTY_ACTION_TYPE = "INTL_MARK_NON_RENEWAL_OF_CONTRACTING_PARTY_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_NON_RENEWAL_OF_CONTRACTING_PARTY_STATUS_CODE = "INTL_MARK_NON_RENEWAL_OF_CONTRACTING_PARTY_STATUS_CODE";
    String EXT_CONFIG_PARAM_INTL_MARK_FORMAL_EXPERTISE_ACTION_TYPE = "INTL_MARK_FORMAL_EXPERTISE_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_WIPO_DIVIDED_ACTION_TYPE = "INTL_MARK_WIPO_DIVIDED_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_WIPO_FULLY_DIVIDED_ACTION_TYPE = "INTL_MARK_WIPO_FULLY_DIVIDED_ACTION_TYPE";
    String EXT_CONFIG_PARAM_ZMR_ACCEPTED_ACTION_TYPE = "ZMR_ACCEPTED_ACTION_TYPE";
    String IPC_LATEST_VERSION = "IPC_LATEST_VERSION";
    String CPC_LATEST_VERSION = "CPC_LATEST_VERSION";
    String EXT_CONFIG_PARAM_ZMR_MADRID_EFILING_ACTION_TYPE = "ZMR_MADRID_EFILING_ACTION_TYPE";
    String EXT_CONFIG_PARAM_INTL_MARK_ACCEPTED_REGISTRATION_STATUS_CODE = "INTL_MARK_ACCEPTED_REGISTRATION_STATUS_CODE";
    String EXT_CONFIG_PARAM_ZMR_IRREGULARITY_LETTER_ACTION_TYPE = "ZMR_IRREGULARITY_LETTER_ACTION_TYPE";
    String EXT_CONFIG_PARAM_ZTR_IRREGULARITY_LETTER_ACTION_TYPE = "ZTR_IRREGULARITY_LETTER_ACTION_TYPE";
    String EXT_CONFIG_PARAM_ZMR_FULL_CESSATION_ACTION_TYPE = "ZMR_FULL_CESSATION_ACTION_TYPE";
    String EXT_CONFIG_PARAM_ZMR_PARTIAL_CESSATION_ACTION_TYPE = "ZMR_PARTIAL_CESSATION_ACTION_TYPE";

    String EXT_GLASSFISH_LOGS_DIR = "GlassfishLogsDir";

    CConfigParam selectConfigByCode(String code);

    CConfigParam selectExtConfigByCode(String code);

}