--liquibase formatted sql

--changeset vnikolov:144
/****** Object:  Index [IP_USERDOC_PERSON_INDEX] ******/
CREATE NONCLUSTERED INDEX [IP_USERDOC_PERSON_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
    [DOC_ORI] ASC,
	[DOC_LOG] ASC,
	[DOC_SER] ASC,
	[DOC_NBR] ASC,
	[PERSON_NBR] ASC,
	[ADDR_NBR] ASC,
	[ROLE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]


