//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.13 at 06:59:50 PM EEST 
//


package bg.duosoft.ipas.integration.tmclass.alpha.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassDescriptionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassDescriptionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassNumber" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}NiceClassNumberType"/>
 *         &lt;element name="GoodsServicesDescription" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}TextType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassDescriptionType", propOrder = {
    "classNumber",
    "goodsServicesDescription"
})
public class ClassDescriptionType {

    @XmlElement(name = "ClassNumber")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int classNumber;
    @XmlElement(name = "GoodsServicesDescription")
    protected List<TextType> goodsServicesDescription;

    /**
     * Gets the value of the classNumber property.
     * 
     */
    public int getClassNumber() {
        return classNumber;
    }

    /**
     * Sets the value of the classNumber property.
     * 
     */
    public void setClassNumber(int value) {
        this.classNumber = value;
    }

    /**
     * Gets the value of the goodsServicesDescription property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the goodsServicesDescription property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGoodsServicesDescription().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextType }
     * 
     * 
     */
    public List<TextType> getGoodsServicesDescription() {
        if (goodsServicesDescription == null) {
            goodsServicesDescription = new ArrayList<TextType>();
        }
        return this.goodsServicesDescription;
    }

}
