//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.13 at 06:59:50 PM EEST 
//


package bg.duosoft.ipas.integration.tmclass.alpha.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EM_CTM-GS_TransactionCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EM_CTM-GS_TransactionCodeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="CTM-GS Goods and Services"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "EM_CTM-GS_TransactionCodeType")
@XmlEnum
public enum EMCTMGSTransactionCodeType {

    @XmlEnumValue("CTM-GS Goods and Services")
    CTM_GS_GOODS_AND_SERVICES("CTM-GS Goods and Services");
    private final String value;

    EMCTMGSTransactionCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EMCTMGSTransactionCodeType fromValue(String v) {
        for (EMCTMGSTransactionCodeType c: EMCTMGSTransactionCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
