//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.13 at 06:59:50 PM EEST 
//


package bg.duosoft.ipas.integration.tmclass.alpha.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GoodsServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsServicesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClassificationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ClassDescriptionDetails" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}ClassDescriptionDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsServicesType", propOrder = {
    "classificationVersion",
    "classDescriptionDetails"
})
public class GoodsServicesType {

    @XmlElement(name = "ClassificationVersion")
    protected String classificationVersion;
    @XmlElement(name = "ClassDescriptionDetails", required = true)
    protected ClassDescriptionDetailsType classDescriptionDetails;

    /**
     * Gets the value of the classificationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationVersion() {
        return classificationVersion;
    }

    /**
     * Sets the value of the classificationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationVersion(String value) {
        this.classificationVersion = value;
    }

    /**
     * Gets the value of the classDescriptionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ClassDescriptionDetailsType }
     *     
     */
    public ClassDescriptionDetailsType getClassDescriptionDetails() {
        return classDescriptionDetails;
    }

    /**
     * Sets the value of the classDescriptionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassDescriptionDetailsType }
     *     
     */
    public void setClassDescriptionDetails(ClassDescriptionDetailsType value) {
        this.classDescriptionDetails = value;
    }

}
