//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.13 at 06:59:50 PM EEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.oami.europa.eu/CTM/CTM-GoodsServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.duosoft.ipas.integration.tmclass.alpha.model;
