//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.13 at 06:59:50 PM EEST 
//


package bg.duosoft.ipas.integration.tmclass.alpha.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionBodyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TransactionContentDetails" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}TransactionContentDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionBodyType", propOrder = {
    "transactionContentDetails"
})
public class TransactionBodyType {

    @XmlElement(name = "TransactionContentDetails", required = true)
    protected TransactionContentDetailsType transactionContentDetails;

    /**
     * Gets the value of the transactionContentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionContentDetailsType }
     *     
     */
    public TransactionContentDetailsType getTransactionContentDetails() {
        return transactionContentDetails;
    }

    /**
     * Sets the value of the transactionContentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionContentDetailsType }
     *     
     */
    public void setTransactionContentDetails(TransactionContentDetailsType value) {
        this.transactionContentDetails = value;
    }

}
