--liquibase formatted sql

--changeset mmurlev:320.1
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('Въз51', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('ДД', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('ЖРО', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('ИЗРM', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('ИОРМ', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРВОМ', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРВП', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРВС', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРВЪЗ', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРИЗРM', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРИЗРБ', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРИОП', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРКОР', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРЛИЦ', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРНПРМ', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРНПРМБ', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРОГР', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРОК', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРОО', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРОП', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРПИР', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРПЛН', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРПЛНПВ', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРППР', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРПРМ', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРПСО', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРРМР', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРСВ', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРСП', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРЧЗБР', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('МРЧЗР', 'B', 'N');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('ОПО', 'B', 'S');
INSERT INTO EXT_RECEPTION.USERDOC_RECEPTION_RELATION (LINKED_USERDOC_TYPE, MAIN_TYPE, IS_VISIBLE) VALUES ('СОНЗМР', 'B', 'N');