--liquibase formatted sql

--changeset dveizov:210.1
DROP INDEX CF_ABDOCS_DOCUMENT_TYPE_ID_uindex ON EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE;

--changeset dveizov:210.2
DELETE FROM EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE WHERE TYPE = 'ИУСО';
DELETE FROM EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE WHERE TYPE = 'Плн';
DELETE FROM EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE WHERE TYPE = 'ППЛН';

INSERT INTO EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE (ABDOCS_DOC_TYPE_ID, TYPE, NAME, IPAS_OBJECT, DOC_REGISTRATION_TYPE)
VALUES (92, N'ИУСО', N'СД - Искане за удължаване срока на отговор', N'USERDOC', 1);

INSERT INTO EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE (ABDOCS_DOC_TYPE_ID, TYPE, NAME, IPAS_OBJECT, DOC_REGISTRATION_TYPE)
VALUES (98, N'Плн', N'ИС - Пълномощно', N'USERDOC', 1);

INSERT INTO EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE (ABDOCS_DOC_TYPE_ID, TYPE, NAME, IPAS_OBJECT, DOC_REGISTRATION_TYPE)
VALUES (169, N'ППЛН', N'ИС - Представяне на пълномощно', N'USERDOC', 1);


