--liquibase formatted sql

--changeset dveizov:214
INSERT INTO EXT_USER.CF_SECURITY_ROLES (ROLE_NAME, DESCRIPTION) VALUES ('userdoc.userdoc-service-scope-data','Вторични действия: Преглед на панел "Обхват на услугата"');
INSERT INTO EXT_CORE.CF_USERDOC_UI_PANEL (PANEL, IND_RECORDAL, NAME, NAME_EN) VALUES ('ServiceScope', 'N', 'Обхват на услугата', 'Service scope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('Въз', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('ЖО', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('ЖРО', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('ИЗРM', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('ИОРМ', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('ИОСПЗ', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('ОПО', 'ServiceScope');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL) VALUES ('СЗ', 'ServiceScope');

DELETE FROM EXT_USER.CF_GROUP_SECURITY_ROLE WHERE ROLE_NAME = 'userdoc.userdoc-goods-data';
DELETE FROM EXT_USER.CF_SECURITY_ROLES WHERE ROLE_NAME = 'userdoc.userdoc-goods-data';
DELETE FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL WHERE PANEL = 'Goods';
DELETE FROM EXT_CORE.CF_USERDOC_UI_PANEL WHERE PANEL = 'Goods';