-- ALTER TABLE [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES] DROP CONSTRAINT [EXTENDED_IP_MARK_NICE_CLASSES_FK]
-- GO

/****** Object:  Table [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES]    Script Date: 27.3.2019 г. 12:47:01 ******/
-- DROP TABLE [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES]
-- GO

/****** Object:  Table [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES]    Script Date: 27.3.2019 г. 12:47:01 ******/
SET ANSI_NULLS ON;

SET QUOTED_IDENTIFIER ON;

CREATE TABLE [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES](
	[FILE_SEQ] [varchar](2) NOT NULL,
	[FILE_TYP] [varchar](1) NOT NULL,
	[FILE_SER] [numeric](4, 0) NOT NULL,
	[FILE_NBR] [numeric](10, 0) NOT NULL,
	[NICE_CLASS_CODE] [numeric](2, 0) NOT NULL,
	[NICE_CLASS_STATUS_WCODE] [varchar](1) NOT NULL,
	[ALL_TERMS_DECLARATION] [varchar](1) NULL,
 CONSTRAINT [PK_EXTENDED_IP_MARK_NICE_CLASSES] PRIMARY KEY CLUSTERED
(
	[FILE_SEQ] ASC,
	[FILE_TYP] ASC,
	[FILE_SER] ASC,
	[FILE_NBR] ASC,
	[NICE_CLASS_CODE] ASC,
	[NICE_CLASS_STATUS_WCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY];

ALTER TABLE [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES]  WITH CHECK ADD  CONSTRAINT [EXTENDED_IP_MARK_NICE_CLASSES_FK] FOREIGN KEY([FILE_NBR], [FILE_SEQ], [FILE_TYP], [FILE_SER], [NICE_CLASS_CODE], [NICE_CLASS_STATUS_WCODE])
REFERENCES [IPASPROD].[IP_MARK_NICE_CLASSES] ([FILE_NBR], [FILE_SEQ], [FILE_TYP], [FILE_SER], [NICE_CLASS_CODE], [NICE_CLASS_STATUS_WCODE])
ON DELETE CASCADE;

ALTER TABLE [EXT_CORE].[EXTENDED_IP_MARK_NICE_CLASSES] CHECK CONSTRAINT [EXTENDED_IP_MARK_NICE_CLASSES_FK];


