--liquibase formatted sql

--changeset murlev:356.1
create table EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS
(
    ATTACHMENT_TYPE_ID       int         not null,
    BOOKMARK_NAME              varchar(50)  not null,
    BOOKMARK_REQUIRED   bit default 0,
    primary key (ATTACHMENT_TYPE_ID,BOOKMARK_NAME),
);

--changeset murlev:356.2
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (4,'BIBLIOGRAPHIC_DATA',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (4,'ABSTRACT',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (4,'DESCRIPTION',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (4,'CLAIMS',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (4,'DRAWINGS',0)

insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (5,'BIBLIOGRAPHIC_DATA',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (5,'ABSTRACT',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (5,'DESCRIPTION',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (5,'CLAIMS',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (5,'DRAWINGS',0)

insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (7,'BIBLIOGRAPHIC_DATA',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (7,'ABSTRACT',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (7,'DESCRIPTION',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (7,'CLAIMS',1)
insert into EXT_CORE.CF_ATTACHMENT_TYPE_BOOKMARKS (ATTACHMENT_TYPE_ID, BOOKMARK_NAME,BOOKMARK_REQUIRED) values (7,'DRAWINGS',0)

--changeset murlev:356.3
alter table ext_core.IP_PATENT_ATTACHMENT add HAS_BOOKMARKS bit default 0;