--liquibase formatted sql

--changeset dveizov:86.1
alter table EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE
    add IPAS_OBJECT varchar(255)
;
--changeset dveizov:86.2
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE
SET IPAS_OBJECT = 'USERDOC'
WHERE ID IN (
    SELECT at.ID
    FROM EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE at
             JOIN CF_USERDOC_TYPE ut on at.TYPE = ut.USERDOC_TYP
)

UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'OFFIDOC' WHERE TYPE = 'ВД';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'OFFIDOC' WHERE TYPE = 'ИК';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'MARK' WHERE TYPE = 'N';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'MARK' WHERE TYPE = 'Г';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'P';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'S';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'U';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'S';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'Д';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'С';
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE SET IPAS_OBJECT = 'PATENT' WHERE TYPE = 'T';


