--liquibase formatted sql

--changeset mmurlev:88.1
ALTER TABLE EXT_CORE.PLANT_TAXON_NOMENCLATURE ADD CLASSIFY_COPY TEXT
;

--changeset mmurlev:88.2
UPDATE EXT_CORE.PLANT_TAXON_NOMENCLATURE SET PLANT_TAXON_NOMENCLATURE.CLASSIFY_COPY = LATIN_CLASSIFY where 1=1
;

UPDATE EXT_CORE.PLANT_TAXON_NOMENCLATURE SET LATIN_CLASSIFY = COMMON_CLASSIFY_ENG where 1=1
;

UPDATE EXT_CORE.PLANT_TAXON_NOMENCLATURE SET COMMON_CLASSIFY_ENG = PLANT_TAXON_NOMENCLATURE.CLASSIFY_COPY where 1=1
;

ALTER TABLE EXT_CORE.PLANT_TAXON_NOMENCLATURE
DROP COLUMN CLASSIFY_COPY;
;

