//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:00:27 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.heading.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EM_CTM-GS_TransactionCodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="EM_CTM-GS_TransactionCodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="CTM-GS Goods and Services"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "EM_CTM-GS_TransactionCodeType")
@XmlEnum
public enum EMCTMGSTransactionCodeType {

    @XmlEnumValue("CTM-GS Goods and Services")
    CTM_GS_GOODS_AND_SERVICES("CTM-GS Goods and Services");
    private final String value;

    EMCTMGSTransactionCodeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static EMCTMGSTransactionCodeType fromValue(String v) {
        for (EMCTMGSTransactionCodeType c: EMCTMGSTransactionCodeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
