//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:00:27 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.heading.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for GoodsServicesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GoodsServicesType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ClassificationVersion" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ClassDescriptionDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ClassDescription" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}ClassDescriptionType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GoodsServicesType", propOrder = {
    "classificationVersion",
    "classDescriptionDetails"
})
public class GoodsServicesType {

    @XmlElement(name = "ClassificationVersion")
    protected String classificationVersion;
    @XmlElement(name = "ClassDescriptionDetails", required = true)
    protected ClassDescriptionDetails classDescriptionDetails;

    /**
     * Gets the value of the classificationVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationVersion() {
        return classificationVersion;
    }

    /**
     * Sets the value of the classificationVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationVersion(String value) {
        this.classificationVersion = value;
    }

    /**
     * Gets the value of the classDescriptionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ClassDescriptionDetails }
     *     
     */
    public ClassDescriptionDetails getClassDescriptionDetails() {
        return classDescriptionDetails;
    }

    /**
     * Sets the value of the classDescriptionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassDescriptionDetails }
     *     
     */
    public void setClassDescriptionDetails(ClassDescriptionDetails value) {
        this.classDescriptionDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ClassDescription" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}ClassDescriptionType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "classDescription"
    })
    public static class ClassDescriptionDetails {

        @XmlElement(name = "ClassDescription", required = true)
        protected List<ClassDescriptionType> classDescription;

        /**
         * Gets the value of the classDescription property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the classDescription property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getClassDescription().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ClassDescriptionType }
         * 
         * 
         */
        public List<ClassDescriptionType> getClassDescription() {
            if (classDescription == null) {
                classDescription = new ArrayList<ClassDescriptionType>();
            }
            return this.classDescription;
        }

    }

}
