//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:00:27 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.heading.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for NiceClassHeadingsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NiceClassHeadingsRequestType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RequestLanguageCode" type="{http://www.w3.org/2001/XMLSchema}language" minOccurs="0"/&gt;
 *         &lt;element name="RequestNiceClass" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NiceClassHeadingsRequestType", propOrder = {
    "requestLanguageCode",
    "requestNiceClass"
})
public class NiceClassHeadingsRequestType {

    @XmlElement(name = "RequestLanguageCode")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "language")
    protected String requestLanguageCode;
    @XmlElement(name = "RequestNiceClass")
    protected String requestNiceClass;

    /**
     * Gets the value of the requestLanguageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestLanguageCode() {
        return requestLanguageCode;
    }

    /**
     * Sets the value of the requestLanguageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestLanguageCode(String value) {
        this.requestLanguageCode = value;
    }

    /**
     * Gets the value of the requestNiceClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestNiceClass() {
        return requestNiceClass;
    }

    /**
     * Sets the value of the requestNiceClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestNiceClass(String value) {
        this.requestNiceClass = value;
    }

}
