//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:00:27 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.heading.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.duosoft.ipas.integration.tmclass.heading.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Transaction_QNAME = new QName("http://www.oami.europa.eu/CTM/CTM-GoodsServices", "Transaction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.duosoft.ipas.integration.tmclass.heading.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GoodsServicesType }
     * 
     */
    public GoodsServicesType createGoodsServicesType() {
        return new GoodsServicesType();
    }

    /**
     * Create an instance of {@link TransactionHeaderType }
     * 
     */
    public TransactionHeaderType createTransactionHeaderType() {
        return new TransactionHeaderType();
    }

    /**
     * Create an instance of {@link TransactionDataType }
     * 
     */
    public TransactionDataType createTransactionDataType() {
        return new TransactionDataType();
    }

    /**
     * Create an instance of {@link TransactionBodyType }
     * 
     */
    public TransactionBodyType createTransactionBodyType() {
        return new TransactionBodyType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link ClassDescriptionType }
     * 
     */
    public ClassDescriptionType createClassDescriptionType() {
        return new ClassDescriptionType();
    }

    /**
     * Create an instance of {@link NiceClassHeadingsRequestType }
     * 
     */
    public NiceClassHeadingsRequestType createNiceClassHeadingsRequestType() {
        return new NiceClassHeadingsRequestType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link GoodsServicesType.ClassDescriptionDetails }
     * 
     */
    public GoodsServicesType.ClassDescriptionDetails createGoodsServicesTypeClassDescriptionDetails() {
        return new GoodsServicesType.ClassDescriptionDetails();
    }

    /**
     * Create an instance of {@link TransactionHeaderType.SenderDetails }
     * 
     */
    public TransactionHeaderType.SenderDetails createTransactionHeaderTypeSenderDetails() {
        return new TransactionHeaderType.SenderDetails();
    }

    /**
     * Create an instance of {@link TransactionDataType.GoodsServicesDetails }
     * 
     */
    public TransactionDataType.GoodsServicesDetails createTransactionDataTypeGoodsServicesDetails() {
        return new TransactionDataType.GoodsServicesDetails();
    }

    /**
     * Create an instance of {@link TransactionBodyType.TransactionContentDetails }
     * 
     */
    public TransactionBodyType.TransactionContentDetails createTransactionBodyTypeTransactionContentDetails() {
        return new TransactionBodyType.TransactionContentDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://www.oami.europa.eu/CTM/CTM-GoodsServices", name = "Transaction")
    public JAXBElement<TransactionType> createTransaction(TransactionType value) {
        return new JAXBElement<TransactionType>(_Transaction_QNAME, TransactionType.class, null, value);
    }

}
