//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:00:27 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.oami.europa.eu/CTM/CTM-GoodsServices", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.duosoft.ipas.integration.tmclass.heading.model;
