//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.25 at 12:00:27 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.heading.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for TransactionDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="NiceClassHeadingsRequest" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}NiceClassHeadingsRequestType" minOccurs="0"/&gt;
 *         &lt;element name="GoodsServicesDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="GoodServices" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}GoodsServicesType" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDataType", propOrder = {
    "niceClassHeadingsRequest",
    "goodsServicesDetails"
})
public class TransactionDataType {

    @XmlElement(name = "NiceClassHeadingsRequest")
    protected NiceClassHeadingsRequestType niceClassHeadingsRequest;
    @XmlElement(name = "GoodsServicesDetails", required = true)
    protected GoodsServicesDetails goodsServicesDetails;

    /**
     * Gets the value of the niceClassHeadingsRequest property.
     * 
     * @return
     *     possible object is
     *     {@link NiceClassHeadingsRequestType }
     *     
     */
    public NiceClassHeadingsRequestType getNiceClassHeadingsRequest() {
        return niceClassHeadingsRequest;
    }

    /**
     * Sets the value of the niceClassHeadingsRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link NiceClassHeadingsRequestType }
     *     
     */
    public void setNiceClassHeadingsRequest(NiceClassHeadingsRequestType value) {
        this.niceClassHeadingsRequest = value;
    }

    /**
     * Gets the value of the goodsServicesDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsServicesDetails }
     *     
     */
    public GoodsServicesDetails getGoodsServicesDetails() {
        return goodsServicesDetails;
    }

    /**
     * Sets the value of the goodsServicesDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsServicesDetails }
     *     
     */
    public void setGoodsServicesDetails(GoodsServicesDetails value) {
        this.goodsServicesDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="GoodServices" type="{http://www.oami.europa.eu/CTM/CTM-GoodsServices}GoodsServicesType" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "goodServices"
    })
    public static class GoodsServicesDetails {

        @XmlElement(name = "GoodServices", required = true)
        protected List<GoodsServicesType> goodServices;

        /**
         * Gets the value of the goodServices property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the goodServices property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGoodServices().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GoodsServicesType }
         * 
         * 
         */
        public List<GoodsServicesType> getGoodServices() {
            if (goodServices == null) {
                goodServices = new ArrayList<GoodsServicesType>();
            }
            return this.goodServices;
        }

    }

}
