/****** Object:  Index [FILE_FK_INDEX]    Script Date: 26/02/2020 11:45:39 AM ******/
CREATE NONCLUSTERED INDEX [FILE_FK_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[FILE_SEQ] ASC,
	[FILE_TYP] ASC,
	[FILE_SER] ASC,
	[FILE_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];


/****** Object:  Index [PROC_FK_INDEX]    Script Date: 26/02/2020 11:46:44 AM ******/
CREATE NONCLUSTERED INDEX [PROC_FK_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[PROC_TYP] ASC,
	[PROC_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY];

/****** Object:  Index [ACTION_FK_INDEX]    Script Date: 26/02/2020 11:46:56 AM ******/
CREATE NONCLUSTERED INDEX [ACTION_FK_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[PROC_TYP] ASC,
	[PROC_NBR] ASC,
	[ACTION_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
;

/****** Object:  Index [PERSON_ADDRESS_FK]    Script Date: 26/02/2020 11:47:09 AM ******/
CREATE NONCLUSTERED INDEX [PERSON_ADDRESS_FK] ON [EXT_CORE].[INDEX_QUEUE]
(
	[PERSON_NBR] ASC,
	[ADDR_NBR] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
;

/****** Object:  Index [VIENNA_CLASS_INDEX]    Script Date: 26/02/2020 11:47:18 AM ******/
CREATE NONCLUSTERED INDEX [VIENNA_CLASS_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[VIENNA_CLASS_CODE] ASC,
	[VIENNA_GROUP_CODE] ASC,
	[VIENNA_ELEM_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
;

/****** Object:  Index [NICE_CLASS_INDEX]    Script Date: 26/02/2020 11:47:28 AM ******/
CREATE NONCLUSTERED INDEX [NICE_CLASS_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[NICE_CLASS_CODE] ASC,
	[NICE_CLASS_STATUS_WCODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
;

/****** Object:  Index [IPC_FK_INDEX]    Script Date: 26/02/2020 11:47:43 AM ******/
CREATE NONCLUSTERED INDEX [IPC_FK_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[IPC_SECTION_CODE] ASC,
	[IPC_CLASS_CODE] ASC,
	[IPC_SUBCLASS_CODE] ASC,
	[IPC_GROUP_CODE] ASC,
	[IPC_SUBGROUP_CODE] ASC,
	[IPC_QUALIFICATION_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
;

/****** Object:  Index [SUMMARY_FK_INDEX]    Script Date: 26/02/2020 11:47:53 AM ******/
CREATE NONCLUSTERED INDEX [SUMMARY_FK_INDEX] ON [EXT_CORE].[INDEX_QUEUE]
(
	[FILE_SEQ] ASC,
	[FILE_TYP] ASC,
	[FILE_SER] ASC,
	[FILE_NBR] ASC,
	[LANGUAGE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
;


