--liquibase formatted sql

--changeset dveizov:82.1 splitStatements:false
CREATE TRIGGER [IPASPROD].[SYNC_ABDOCS_PERSON_AFTER_UPDATE]
    ON [IPASPROD].[IP_PERSON]
    AFTER UPDATE
    AS
BEGIN
    SET NOCOUNT ON;

    -- update
    IF EXISTS(SELECT * FROM inserted) AND EXISTS(SELECT * FROM deleted)
        BEGIN
            INSERT INTO [EXT_CORE].[IP_PERSON_ABDOCS_SYNC](PERSON_NBR, ADDR_NBR, INSERTED_AT)
            SELECT pa.PERSON_NBR, pa.ADDR_NBR, GETDATE()
            FROM inserted i
                     JOIN [IPASPROD].[IP_PERSON_ADDRESSES] pa on pa.PERSON_NBR = i.PERSON_NBR
        END
END
;

ALTER TABLE [IPASPROD].[IP_PERSON]
    ENABLE TRIGGER [SYNC_ABDOCS_PERSON_AFTER_UPDATE]
;

--changeset dveizov:82.2 splitStatements:false
CREATE TRIGGER [IPASPROD].[SYNC_ABDOCS_PERSON_ADDRESS_AFTER_UPDATE]
    ON [IPASPROD].[IP_PERSON_ADDRESSES]
    AFTER UPDATE
    AS
BEGIN
    SET NOCOUNT ON;

    -- update
    IF EXISTS(SELECT * FROM inserted) AND EXISTS(SELECT * FROM deleted)
        BEGIN
            INSERT INTO [EXT_CORE].[IP_PERSON_ABDOCS_SYNC](PERSON_NBR, ADDR_NBR, INSERTED_AT)
            SELECT i.PERSON_NBR, i.ADDR_NBR, GETDATE()
            FROM inserted i
        END
END
;

ALTER TABLE [IPASPROD].[IP_PERSON_ADDRESSES]
    ENABLE TRIGGER [SYNC_ABDOCS_PERSON_ADDRESS_AFTER_UPDATE]
;

