--liquibase formatted sql

--changeset mmurlev:80.1
ALTER TABLE IP_PATENT_DRAWINGS ADD DRAWING_NBR_COPY numeric(15);
ALTER TABLE IP_PATENT_DRAWINGS ADD IMAGE_REFUSED bit;
ALTER TABLE IP_PATENT_DRAWINGS ADD IMAGE_PUBLISHED bit;
ALTER TABLE IP_PATENT_DRAWINGS ADD VIEW_TYPE_ID numeric(3);

--changeset mmurlev:80.2
UPDATE IP_PATENT_DRAWINGS SET DRAWING_NBR_COPY = DRAWING_NBR where FILE_TYP IN ('Е','У');

UPDATE IP_PATENT_DRAWINGS SET VIEW_TYPE_ID = RIGHT(DRAWING_NBR,1) where FILE_TYP IN ('Е','У');

update IP_PATENT_DRAWINGS set DRAWING_NBR_COPY = CAST(((RIGHT(DRAWING_NBR,3) -100) - VIEW_TYPE_ID) / 10  AS INT) where FILE_TYP IN ('Е','У');

UPDATE IP_PATENT_DRAWINGS
SET IMAGE_PUBLISHED =  CASE
                        WHEN LEN(DRAWING_NBR) = 3 THEN 1
                        WHEN (CAST(RIGHT(DRAWING_NBR,4) AS INT) - CAST(RIGHT(DRAWING_NBR,3) AS INT))  = 0 THEN 1
                        ELSE 0
                    END
WHERE FILE_TYP IN ('Е','У');

UPDATE IP_PATENT_DRAWINGS
SET IMAGE_REFUSED =  CASE
                        WHEN LEN(DRAWING_NBR) = 4 THEN 0
                        WHEN (CAST(RIGHT(DRAWING_NBR,5) AS INT) - CAST(RIGHT(DRAWING_NBR,4) AS INT))  = 0 THEN 0
                        ELSE 1
                    END
WHERE FILE_TYP IN ('Е','У');

-- The only broken single design fix
update IP_PATENT_DRAWINGS set DRAWING_NBR_COPY = (CAST(LEFT(DRAWING_NBR,3) AS INT) - 10) WHERE LEN(DRAWING_NBR) > 3 and FILE_TYP = 'У' and file_nbr = 472001;
update IP_PATENT_DRAWINGS set IMAGE_PUBLISHED = 1, IMAGE_REFUSED = 0 WHERE LEN(DRAWING_NBR) > 3 and FILE_TYP = 'У' and file_nbr = 472001;
----------------------------------------

UPDATE IP_PATENT_DRAWINGS SET DRAWING_NBR = DRAWING_NBR_COPY WHERE  FILE_TYP IN ('Е','У');

INSERT INTO EXT_CORE.SINGLE_DESIGN_EXTENDED(FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, DRAWING_NBR, IMAGE_REFUSED, IMAGE_PUBLISHED, VIEW_TYPE_ID)
SELECT FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, DRAWING_NBR, IMAGE_REFUSED, IMAGE_PUBLISHED, VIEW_TYPE_ID FROM IP_PATENT_DRAWINGS WHERE  FILE_TYP IN ('Е','У');

ALTER TABLE IP_PATENT_DRAWINGS
DROP COLUMN DRAWING_NBR_COPY;

ALTER TABLE IP_PATENT_DRAWINGS
DROP COLUMN VIEW_TYPE_ID;

ALTER TABLE IP_PATENT_DRAWINGS
DROP COLUMN IMAGE_REFUSED;

ALTER TABLE IP_PATENT_DRAWINGS
DROP COLUMN IMAGE_PUBLISHED;

