CREATE TABLE ipasprod.EXT_CORE.IP_PATENT_TRANSFORMATION
(
    FILE_SEQ VARCHAR(2) NOT NULL,
    FILE_TYP VARCHAR(1) NOT NULL,
    FILE_SER NUMERIC(4) NOT NULL,
    FILE_NBR NUMERIC(10) NOT NULL,
    TRANSFORM_TYPE VARCHAR(2),
    APPL_ID VARCHAR(50),
    APPL_DATE DATETIME,
    PUBL_ID VARCHAR(50),
    PUBL_DATE DATETIME,
    PUBL_COUNTRY VARCHAR(10),
    CONSTRAINT IP_PATENT_TRANSFORMATION_PK PRIMARY KEY (FILE_SEQ, FILE_TYP, FILE_NBR, FILE_SER)
)


ALTER TABLE ipasprod.EXT_CORE.IP_PATENT_TRANSFORMATION
ADD CONSTRAINT IP_PATENT_TRANSFORMATION_FK
FOREIGN KEY (FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER ) REFERENCES IPASPROD.IP_PATENT (FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER)

