CREATE TABLE ipasprod.EXT_CORE.IP_PATENT_ATTACHMENTS
(
    FILE_SEQ VARCHAR(2) NOT NULL,
    FILE_TYP VARCHAR(1) NOT NULL,
    FILE_SER NUMERIC(4) NOT NULL,
    FILE_NBR NUMERIC(10) NOT NULL,
    DRAWINGS_CNT NUMERIC(10),
    DRAWING_PUBL NUMERIC(10),
    DESCRIPTION_PAGES_CNT NUMERIC(10),
    CLAIMS_CNT NUMERIC(10),
    DRAWING_DATA IMAGE,
    CLAIM_DATA IMAGE,
    DESCRIPTION_DATA IMAGE,
    CONSTRAINT IP_PATENT_ATTACHMENTS_PK PRIMARY KEY (FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER)
)


ALTER TABLE ipasprod.EXT_CORE.IP_PATENT_ATTACHMENTS
ADD CONSTRAINT IP_PATENT_ATTACHMENTS_FK
FOREIGN KEY (FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER ) REFERENCES IPASPROD.IP_PATENT (FILE_NBR, FILE_SEQ, FILE_TYP, FILE_SER)

