--liquibase formatted sql

--changeset mmurlev:329.1
alter table ext_Core.CF_ATTACHMENT_TYPE add ATTACHMENT_ORDER integer;
alter table ext_Core.CF_ATTACHMENT_TYPE add ATTACHMENT_FILE_TYPES VARCHAR(50);

--changeset mmurlev:329.2
insert into ext_Core.CF_ATTACHMENT_TYPE (id, name, ATTACHMENT_NAME_SUFFIX, ATTACHMENT_ORDER, ATTACHMENT_FILE_TYPES)
values(16,'Описание за публикация Т3 (коригиран)','Т3',7,'T');

insert into ext_Core.CF_ATTACHMENT_TYPE (id, name, ATTACHMENT_NAME_SUFFIX, ATTACHMENT_ORDER, ATTACHMENT_FILE_TYPES)
values(17,'"Описание за публикация Т4 (коригиран)','Т4',9,'T');

insert into ext_Core.CF_ATTACHMENT_TYPE (id, name, ATTACHMENT_NAME_SUFFIX, ATTACHMENT_ORDER, ATTACHMENT_FILE_TYPES)
values(18,'Описание за публикация Т6 (коригиран)','Т6',12,'T');


--changeset mmurlev:329.3
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 1 WHERE ID = 4;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 2 WHERE ID = 5;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 3 WHERE ID = 6;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 4 WHERE ID = 14;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 5 WHERE ID = 9;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 6 WHERE ID = 10;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 8 WHERE ID = 11;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 10 WHERE ID = 12;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 11 WHERE ID = 13;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 13 WHERE ID = 7;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 14 WHERE ID = 8;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 15 WHERE ID = 15;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 16 WHERE ID = 3;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 17 WHERE ID = 2;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_ORDER = 18 WHERE ID = 1;
UPDATE  ext_Core.CF_ATTACHMENT_TYPE SET ATTACHMENT_FILE_TYPES = 'U,T,P' WHERE ATTACHMENT_FILE_TYPES is null;
