--liquibase formatted sql

--changeset mmihova:330.1
ALTER TABLE EXT_CORE.IP_MARK_OLD_INTL_REGISTRATION ADD EXTERNAL_SYSTEM_ID varchar (50);
ALTER TABLE EXT_CORE.IP_MARK_OLD_INTL_REGISTRATION ADD HAS_ABDOCS_RECORD bit;