//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.03.07 at 02:28:02 PM EET 
//


package bg.duosoft.ipas.integration.tmseniority.model;

import javax.xml.bind.annotation.*;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for SeniorityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SeniorityType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="SeniorityApplicationNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SeniorityApplicationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="SeniorityRegistrationDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="SeniorityMarkName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SeniorityType", propOrder = {
    "seniorityApplicationNumber",
    "seniorityApplicationDate",
    "seniorityRegistrationDate",
    "seniorityMarkName"
})
public class SeniorityType {

    @XmlElement(name = "SeniorityApplicationNumber")
    protected String seniorityApplicationNumber;
    @XmlElement(name = "SeniorityApplicationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar seniorityApplicationDate;
    @XmlElement(name = "SeniorityRegistrationDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar seniorityRegistrationDate;
    @XmlElement(name = "SeniorityMarkName")
    protected String seniorityMarkName;

    /**
     * Gets the value of the seniorityApplicationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeniorityApplicationNumber() {
        return seniorityApplicationNumber;
    }

    /**
     * Sets the value of the seniorityApplicationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeniorityApplicationNumber(String value) {
        this.seniorityApplicationNumber = value;
    }

    /**
     * Gets the value of the seniorityApplicationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSeniorityApplicationDate() {
        return seniorityApplicationDate;
    }

    /**
     * Sets the value of the seniorityApplicationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSeniorityApplicationDate(XMLGregorianCalendar value) {
        this.seniorityApplicationDate = value;
    }

    /**
     * Gets the value of the seniorityRegistrationDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getSeniorityRegistrationDate() {
        return seniorityRegistrationDate;
    }

    /**
     * Sets the value of the seniorityRegistrationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setSeniorityRegistrationDate(XMLGregorianCalendar value) {
        this.seniorityRegistrationDate = value;
    }

    /**
     * Gets the value of the seniorityMarkName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSeniorityMarkName() {
        return seniorityMarkName;
    }

    /**
     * Sets the value of the seniorityMarkName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSeniorityMarkName(String value) {
        this.seniorityMarkName = value;
    }

}
