--liquibase formatted sql

--changeset mmihova:290.1
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('INTL_MARK_CANCELLATION_ACTION_TYPE', '1368');
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('INTL_MARK_CANCELLATION_STATUS_CODE', '891');

INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('INTL_MARK_NON_RENEWAL_OF_TRADEMARK_ACTION_TYPE', '3363');
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('INTL_MARK_NON_RENEWAL_OF_TRADEMARK_STATUS_CODE', '1344');

INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('INTL_MARK_NON_RENEWAL_OF_CONTRACTING_PARTY_ACTION_TYPE', '3364');
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('INTL_MARK_NON_RENEWAL_OF_CONTRACTING_PARTY_STATUS_CODE', '1346');