--liquibase formatted sql

--changeset mmihova:293.1
CREATE TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG (
  USERDOC_TYP varchar(7) not null,
  CHANGE_MARK_OWNER varchar(1),
  CHANGE_MARK_REPRESENTATIVE varchar(1),
  CHANGE_MARK_RENEWAL_EXPIRATION_DATE varchar(1),
  INSERT_MARK_ACTION_PROTECTION_SURRENDER varchar(1),
  INSERT_MARK_ACTION_CANCELLATION varchar(1),
  INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK varchar(1),
  INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY varchar(1),
  primary key (USERDOC_TYP)
);

--changeset mmihova:293.2
INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРИОП','N','N','N','S', 'N', 'N', 'N');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРИЗРM','N','N','N','N', 'S', 'N', 'N');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРНПРМ','N','N','N','N', 'N', 'S', 'N');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРНПРМБ','N','N','N','N', 'N', 'N', 'S');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРПИР','S','N','N','N', 'N', 'N', 'N');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРПЛН','N','S','N','N', 'N', 'N', 'N');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРППР','S','N','N','N', 'N', 'N', 'N');

INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, CHANGE_MARK_OWNER, CHANGE_MARK_REPRESENTATIVE, CHANGE_MARK_RENEWAL_EXPIRATION_DATE, INSERT_MARK_ACTION_PROTECTION_SURRENDER, INSERT_MARK_ACTION_CANCELLATION, INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK, INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY)
VALUES('МРПРМ','N','N','S','N', 'N', 'N', 'N');


