--liquibase formatted sql

--changeset dveizov:279.1
create table EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE
(
    CODE                  varchar(255)
        constraint PK_CF_USERDOC_EXTRA_DATA_TYPE
            primary key,
    TITLE                 varchar(255),
    TITLE_EN              varchar(255),
    IS_TEXT               bit default 0,
    IS_NUMBER             bit default 0,
    IS_DATE               bit default 0,
    IS_BOOLEAN            bit default 0,
    BOOLEAN_TEXT_TRUE     varchar(500),
    BOOLEAN_TEXT_FALSE    varchar(500),
    BOOLEAN_TEXT_TRUE_EN  varchar(500),
    BOOLEAN_TEXT_FALSE_EN varchar(500),
);

--changeset dveizov:279.2
create table EXT_CORE.IP_USERDOC_EXTRA_DATA
(
    DOC_ORI       varchar(4)  not null,
    DOC_LOG       varchar(1)  not null,
    DOC_SER       numeric(4)  not null,
    DOC_NBR       numeric(15) not null,
    CODE          varchar(255)  not null,
    TEXT_VALUE    varchar(2000),
    NUMBER_VALUE  numeric(8),
    DATE_VALUE    datetime,
    BOOLEAN_VALUE bit,
    constraint IP_USERDOC_EXTRA_DATA_PK
        primary key nonclustered (DOC_NBR, DOC_ORI, DOC_LOG, DOC_SER, CODE),
    constraint IP_USERDOC_EXTRA_DATA_IP_USERDOC_FK
        foreign key (DOC_NBR, DOC_ORI, DOC_LOG, DOC_SER) references IPASPROD.IP_USERDOC
            on update cascade on delete cascade,
    constraint IP_USERDOC_EXTRA_DATA_EXTRA_DATA_TYPE_FK
        foreign key (CODE) references EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE
);

--changeset dveizov:279.3
create table EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL
(
    CODE varchar(255)  not null
        constraint CF_USERDOC_EXTRA_DATA_TO_UI_PANEL_CODE_fk
            references EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE,
    PANEL       varchar(50) not null
        constraint CF_USERDOC_EXTRA_DATA_TO_UI_PANEL_PANEL_fk
            references EXT_CORE.CF_USERDOC_UI_PANEL,
    constraint CF_USERDOC_EXTRA_DATA_TO_PANEL_pk
        primary key nonclustered (CODE, PANEL)
);

--changeset dveizov:279.4
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('DESCRIPTION', N'Описание', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_DATE) VALUES ('EFFECTIVE_DATE', N'Дата на влизане в сила', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_DATE) VALUES ('INVALIDATION_DATE', N'Дата на заличаване', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE) VALUES ('SERVICE_SCOPE', N'Обхват на услугата', 1, N'Всички', N'Част');

--Claim
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_NUMBER) VALUES ('CLAIM_CONTESTED_DECISION_NUMBER', N'Обжалвано решение: номер', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_DATE) VALUES ('CLAIM_CONTESTED_DECISION_DATE', N'Обжалвано решение: дата', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('CLAIM_MOTIVE', N'Мотиви', 1);

--Bankruptcy
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('BANKRUPTCY_CASE_NUMBER', N'Номер на делото', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('BANKRUPTCY_COURT_NAME', N'Съд, в който е образувано делото', 1);

--Licenses
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('LICENSE_CONTRACT_NUMBER_AND_DATE', N'Номер и дата на лицензионен договор', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('LICENSE_TERRITORIAL_RESTRICTION', N'Териториално ограничение', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('LICENSE_SUBLICENSE_IDENTIFIER', N'Идентификатор на лицензия', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_DATE) VALUES ('LICENSE_EXPIRATION_DATE', N'Дата', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE) VALUES ('LICENSE_EXPIRATION_DATE_TYPE', N'Срок', 1, N'До зададена дата', N'До изтичнае на срока на действие на марката(обекта)');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE, BOOLEAN_TEXT_TRUE_EN, BOOLEAN_TEXT_FALSE_EN) VALUES ('LICENSE_SUBLICENSE_GRANT_RIGHT', N'Право на предоставяне на сублицензия', 1, N'Да', N'Не', 'Yes', 'No');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE) VALUES ('LICENSE_TERRITORIAL_SCOPE', N'Териториален обхват', 1, N'За цялата територия на Република България', N'За част от територията на Република България');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE, BOOLEAN_TEXT_TRUE_EN, BOOLEAN_TEXT_FALSE_EN) VALUES ('LICENSE_SUBLICENSE', N'Сублицензия', 1, N'Да', N'Не', 'Yes', 'No');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE, BOOLEAN_TEXT_TRUE_EN, BOOLEAN_TEXT_FALSE_EN) VALUES ('LICENSE_IS_COMPULSORY', N'Принудителна', 1, N'Да', N'Не', 'Yes', 'No');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE) VALUES ('LICENSE_TYPE', N'Вид на лицензията', 1, N'Изключителна', N'Неизключителна');

--Pledge
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('PLEDGE_EXPIRATION_DATE', N'Срок', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('PLEDGE_DESCRIPTION', N'Описание на обезпеченото вземане', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('PLEDGE_ADDITIONAL_DATA', N'Други данни', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('PLEDGE_AMOUNT', N'Сума', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('PLEDGE_INTEREST', N'Лихви', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT) VALUES ('PLEDGE_PENALTY', N'Неустойки', 1);
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_NUMBER) VALUES ('PLEDGE_SEQUENCE_NUMBER', N'Пореден номер', 1);

--Renewal
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_DATE) VALUES ('RENEWAL_NEW_EXPIRATION_DATE', N'Нов срок на закрила', 1);

--Security_measure
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE, BOOLEAN_TEXT_TRUE_EN, BOOLEAN_TEXT_FALSE_EN) VALUES ('SECURITY_MEASURE_PROHIBITION_RIGHTS_USE', N'Забрана за използване на правата върху марка от притежателя или лицензополучателя', 1, N'Да', N'Не', 'Yes', 'No');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_BOOLEAN, BOOLEAN_TEXT_TRUE, BOOLEAN_TEXT_FALSE, BOOLEAN_TEXT_TRUE_EN, BOOLEAN_TEXT_FALSE_EN) VALUES ('SECURITY_MEASURE_PROHIBITION_RIGHTS_MANAGE', N'Забрана за разпореждане с правата върху марка от притежателя или лицензополучателя на изключителна лицензия', 1, N'Да', N'Не', 'Yes', 'No');

--Transfer
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TYPE (CODE, TITLE, IS_TEXT)VALUES ('TRANSFER_INVALIDATION_REASON', N'Основание за заличаване', 1);

--changeset dveizov:279.5
--Claim
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('CLAIM_CONTESTED_DECISION_NUMBER', 'Claim');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('CLAIM_CONTESTED_DECISION_DATE', 'Claim');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('CLAIM_MOTIVE', 'Claim');

--Bankruptcy
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Bankruptcy');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('INVALIDATION_DATE', 'Bankruptcy');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('DESCRIPTION', 'Bankruptcy');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('BANKRUPTCY_CASE_NUMBER', 'Bankruptcy');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('BANKRUPTCY_COURT_NAME', 'Bankruptcy');

--Licenses
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('INVALIDATION_DATE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('SERVICE_SCOPE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('DESCRIPTION', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_CONTRACT_NUMBER_AND_DATE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_TERRITORIAL_RESTRICTION', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_SUBLICENSE_IDENTIFIER', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_EXPIRATION_DATE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_EXPIRATION_DATE_TYPE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_SUBLICENSE_GRANT_RIGHT', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_TERRITORIAL_SCOPE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_SUBLICENSE', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_IS_COMPULSORY', 'Licenses');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('LICENSE_TYPE', 'Licenses');

--Pledge
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('INVALIDATION_DATE', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_EXPIRATION_DATE', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_DESCRIPTION', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_ADDITIONAL_DATA', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_AMOUNT', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_INTEREST', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_PENALTY', 'Pledge');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('PLEDGE_SEQUENCE_NUMBER', 'Pledge');

--Renewal
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL)VALUES ('EFFECTIVE_DATE', 'Renewal');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL)VALUES ('SERVICE_SCOPE', 'Renewal');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL)VALUES ('RENEWAL_NEW_EXPIRATION_DATE', 'Renewal');

--Security_measure
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL)VALUES ('EFFECTIVE_DATE', 'Security_measure');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('INVALIDATION_DATE', 'Security_measure');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('DESCRIPTION', 'Security_measure');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('SECURITY_MEASURE_PROHIBITION_RIGHTS_USE', 'Security_measure');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('SECURITY_MEASURE_PROHIBITION_RIGHTS_MANAGE', 'Security_measure');

--Transfer
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Transfer');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('INVALIDATION_DATE', 'Transfer');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('SERVICE_SCOPE', 'Transfer');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('TRANSFER_INVALIDATION_REASON', 'Transfer');

--Withdrawal
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Withdrawal');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('SERVICE_SCOPE', 'Withdrawal');
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('DESCRIPTION', 'Withdrawal');

--Change_representative
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Change_representative');

--Change
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Change');

--Change_correspondence_address
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('EFFECTIVE_DATE', 'Change_correspondence_address');

--ServiceScope
INSERT INTO EXT_CORE.CF_USERDOC_EXTRA_DATA_TO_UI_PANEL (CODE, PANEL) VALUES ('SERVICE_SCOPE', 'ServiceScope');


