--liquibase formatted sql

--changeset ggeorgiev:279.1
alter table EXT_JOURNAL.JOURNAL_ELEMENT add PROC_TYP as coalesce(ACTION_PROC_TYPE,ACTIONUDOC_PROC_TYPE);
alter table EXT_JOURNAL.JOURNAL_ELEMENT add PROC_NBR as coalesce(ACTION_PROC_NBR,ACTIONUDOC_PROC_NBR);
alter table EXT_JOURNAL.JOURNAL_ELEMENT add ACTION_NBR as coalesce(ACTION_ACTION_NBR,ACTIONUDOC_ACTION_NBR);


CREATE  INDEX [JOURNAL_ELEMENT_ACTION] ON [EXT_JOURNAL].[JOURNAL_ELEMENT] (
     [PROC_TYP] ASC,
     [PROC_NBR] ASC,
     [ACTION_NBR] ASC
);

drop view [EXT_JOURNAL].[VW_JOURNAL];
CREATE VIEW [EXT_JOURNAL].[VW_JOURNAL] AS
SELECT
    j.CODE,
    LEFT(j.code, 4)												as YEAR,
    SUBSTRING(j.code, 5, LEN(j.code))							as BULETIN,
    n.NODE_DEF_NBR												as SECT,
    nd.NAME														as SECT_DEF,
    PROC_TYP,
    PROC_NBR,
    ACTION_NBR
FROM EXT_JOURNAL.JOURNAL_ELEMENT e
         JOIN EXT_JOURNAL.JOURNAL j on e.JOURNAL_NBR = j.JOURNAL_NBR
         JOIN EXT_JOURNAL.JOURNAL_STRUCT_NODE n on e.JOURNAL_STRUCT_NODE_NBR = n.NODE_NBR
         JOIN [EXT_JOURNAL].[NODE_DEFINITION] nd on nd.NODE_DEF_NBR = n.NODE_DEF_NBR;