--liquibase formatted sql

--changeset dveizov:281.1

-- Claim
-- CLAIM_MOTIVE DATA_TEXT1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'CLAIM_MOTIVE', d.DATA_TEXT1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Claim' and d.DATA_TEXT1 is not null;
-- CLAIM_CONTESTED_DECISION_NUMBER DATA_NBR1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, NUMBER_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'CLAIM_CONTESTED_DECISION_NUMBER', d.DATA_NBR1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Claim' and d.DATA_NBR1 is not null;
-- CLAIM_CONTESTED_DECISION_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'CLAIM_CONTESTED_DECISION_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Claim' and d.DATA_DATE1 is not null;

-- Bankruptcy
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Bankruptcy' and d.DATA_DATE1 is not null;
-- INVALIDATION_DATE DATA_DATE5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'INVALIDATION_DATE', d.DATA_DATE5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Bankruptcy' and d.DATA_DATE5 is not null;
-- BANKRUPTCY_CASE_NUMBER DATA_TEXT1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'BANKRUPTCY_CASE_NUMBER', d.DATA_TEXT1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Bankruptcy' and d.DATA_TEXT1 is not null;
-- BANKRUPTCY_COURT_NAME DATA_TEXT2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'BANKRUPTCY_COURT_NAME', d.DATA_TEXT2
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Bankruptcy' and d.DATA_TEXT2 is not null;

-- Licenses
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_DATE1 is not null;
-- INVALIDATION_DATE DATA_DATE5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'INVALIDATION_DATE', d.DATA_DATE5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_DATE5 is not null;
-- LICENSE_EXPIRATION_DATE DATA_DATE2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_EXPIRATION_DATE', d.DATA_DATE2
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_DATE2 is not null;
-- LICENSE_CONTRACT_NUMBER_AND_DATE DATA_TEXT1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_CONTRACT_NUMBER_AND_DATE', d.DATA_TEXT1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_TEXT1 is not null;
-- LICENSE_TERRITORIAL_RESTRICTION DATA_TEXT4
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_TERRITORIAL_RESTRICTION', d.DATA_TEXT4
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_TEXT4 is not null;
-- LICENSE_SUBLICENSE_IDENTIFIER DATA_TEXT5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_SUBLICENSE_IDENTIFIER', d.DATA_TEXT5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_TEXT5 is not null;
-- LICENSE_SUBLICENSE_GRANT_RIGHT DATA_FLAG1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_SUBLICENSE_GRANT_RIGHT',
       CASE
           WHEN d.DATA_FLAG1 = 'S' THEN 1
           WHEN d.DATA_FLAG1 = 'N' THEN 0
        END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_FLAG1 is not null;
-- LICENSE_EXPIRATION_DATE_TYPE DATA_FLAG2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_EXPIRATION_DATE_TYPE',
       CASE
           WHEN d.DATA_FLAG2 = 'S' THEN 1
           WHEN d.DATA_FLAG2 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_FLAG2 is not null;
-- SERVICE_SCOPE DATA_FLAG3
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SERVICE_SCOPE',
       CASE
           WHEN d.DATA_FLAG3 = 'S' THEN 1
           WHEN d.DATA_FLAG3 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_FLAG3 is not null;
-- LICENSE_TERRITORIAL_SCOPE DATA_FLAG4
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_TERRITORIAL_SCOPE',
       CASE
           WHEN d.DATA_FLAG4 = 'S' THEN 1
           WHEN d.DATA_FLAG4 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_FLAG4 is not null;
-- LICENSE_SUBLICENSE DATA_FLAG5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_SUBLICENSE',
       CASE
           WHEN d.DATA_FLAG5 = 'S' THEN 1
           WHEN d.DATA_FLAG5 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.DATA_FLAG5 is not null;
-- LICENSE_TYPE IND_EXCLUSIVE_LICENSE
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_TYPE',
       CASE
           WHEN d.IND_EXCLUSIVE_LICENSE = 'S' THEN 1
           WHEN d.IND_EXCLUSIVE_LICENSE = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_USERDOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.IND_EXCLUSIVE_LICENSE is not null;
-- LICENSE_IS_COMPULSORY IND_COMPULSORY_LICENSE
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'LICENSE_IS_COMPULSORY',
       CASE
           WHEN d.IND_COMPULSORY_LICENSE = 'S' THEN 1
           WHEN d.IND_COMPULSORY_LICENSE = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_USERDOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Licenses' and d.IND_COMPULSORY_LICENSE is not null;

-- Pledge
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_DATE1 is not null;
-- INVALIDATION_DATE DATA_DATE5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'INVALIDATION_DATE', d.DATA_DATE5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_DATE5 is not null;
-- PLEDGE_EXPIRATION_DATE DATA_DATE2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_EXPIRATION_DATE', convert(varchar,d.DATA_DATE2,4)
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_DATE2 is not null;
-- PLEDGE_DESCRIPTION DATA_TEXT1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_DESCRIPTION', d.DATA_TEXT1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_TEXT1 is not null;
-- PLEDGE_ADDITIONAL_DATA DATA_TEXT2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_ADDITIONAL_DATA', d.DATA_TEXT2
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_TEXT2 is not null;
-- PLEDGE_AMOUNT DATA_TEXT3
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_AMOUNT', d.DATA_TEXT3
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_TEXT3 is not null;
-- PLEDGE_INTEREST DATA_TEXT4
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_INTEREST', d.DATA_TEXT4
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_TEXT4 is not null;
-- PLEDGE_PENALTY DATA_TEXT5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_PENALTY', d.DATA_TEXT5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_TEXT5 is not null;
-- PLEDGE_SEQUENCE_NUMBER DATA_NBR1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'PLEDGE_SEQUENCE_NUMBER', d.DATA_NBR1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Pledge' and d.DATA_NBR1 is not null;

-- Renewal
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Renewal' and d.DATA_DATE1 is not null;
-- RENEWAL_NEW_EXPIRATION_DATE DATA_DATE2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'RENEWAL_NEW_EXPIRATION_DATE', d.DATA_DATE2
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Renewal' and d.DATA_DATE2 is not null;
-- SERVICE_SCOPE DATA_FLAG3
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SERVICE_SCOPE',
       CASE
           WHEN d.DATA_FLAG3 = 'S' THEN 1
           WHEN d.DATA_FLAG3 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Renewal' and d.DATA_FLAG3 is not null;

-- Security_measure
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Security_measure' and d.DATA_DATE1 is not null;
-- INVALIDATION_DATE
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'INVALIDATION_DATE', d.DATA_DATE5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Security_measure' and d.DATA_DATE5 is not null;
-- SECURITY_MEASURE_PROHIBITION_RIGHTS_USE DATA_FLAG1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SECURITY_MEASURE_PROHIBITION_RIGHTS_USE',
       CASE
           WHEN d.DATA_FLAG1 = 'S' THEN 1
           WHEN d.DATA_FLAG1 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Security_measure' and d.DATA_FLAG1 is not null;
-- SECURITY_MEASURE_PROHIBITION_RIGHTS_MANAGE DATA_FLAG2
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SECURITY_MEASURE_PROHIBITION_RIGHTS_MANAGE',
       CASE
           WHEN d.DATA_FLAG2 = 'S' THEN 1
           WHEN d.DATA_FLAG2 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Security_measure' and d.DATA_FLAG2 is not null;

-- Transfer
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Transfer' and d.DATA_DATE1 is not null;
-- INVALIDATION_DATE DATA_DATE5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'INVALIDATION_DATE', d.DATA_DATE5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Transfer' and d.DATA_DATE5 is not null;
-- TRANSFER_INVALIDATION_REASON DATA_TEXT5
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, TEXT_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'TRANSFER_INVALIDATION_REASON', d.DATA_TEXT5
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Transfer' and d.DATA_TEXT5 is not null;
-- SERVICE_SCOPE DATA_FLAG3
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SERVICE_SCOPE',
       CASE
           WHEN d.DATA_FLAG3 = 'S' THEN 1
           WHEN d.DATA_FLAG3 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Transfer' and d.DATA_FLAG3 is not null;

-- Withdrawal
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Withdrawal' and d.DATA_DATE1 is not null;
-- SERVICE_SCOPE DATA_FLAG3
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SERVICE_SCOPE',
       CASE
           WHEN d.DATA_FLAG3 = 'S' THEN 1
           WHEN d.DATA_FLAG3 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Withdrawal' and d.DATA_FLAG3 is not null;

-- Change_representative
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Change_representative' and d.DATA_DATE1 is not null;

-- Change
-- EFFECTIVE_DATE DATA_DATE1
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Change' and d.DATA_DATE1 is not null;

-- Change_correspondence_address
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, DATE_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'EFFECTIVE_DATE', d.DATA_DATE1
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'Change_correspondence_address' and d.DATA_DATE1 is not null;

-- ServiceScope
-- SERVICE_SCOPE DATA_FLAG3
INSERT INTO EXT_CORE.IP_USERDOC_EXTRA_DATA (DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, CODE, BOOLEAN_VALUE)
SELECT p.DOC_ORI, p.DOC_LOG, p.DOC_SER, p.DOC_NBR,'SERVICE_SCOPE',
       CASE
           WHEN d.DATA_FLAG3 = 'S' THEN 1
           WHEN d.DATA_FLAG3 = 'N' THEN 0
           END
FROM EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL tui
         join EXT_CORE.CF_USERDOC_UI_PANEL up on tui.PANEL = up.PANEL
         join IPASPROD.IP_PROC p on p.USERDOC_TYP = tui.USERDOC_TYP
         JOIN IPASPROD.IP_DOC d
              on d.DOC_ORI = p.DOC_ORI AND d.DOC_LOG = p.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
where up.PANEL = 'ServiceScope' and d.DATA_FLAG3 is not null;