--liquibase formatted sql

--changeset ggeorgiev:281.1

CREATE VIEW [EXT_CORE].[VW_DOC_INDEX] AS
SELECT d.DOC_ORI, d.DOC_LOG, d.DOC_SER, d.DOC_NBR, d.DOC_SEQ_NBR, d.DOC_SEQ_TYP, d.EXTERNAL_SYSTEM_ID, d.FILING_DATE,
       p.PROC_TYP, p.PROC_NBR, p.STATUS_CODE, p.USERDOC_TYP,
       p.USERDOC_FILE_SEQ FILE_SEQ, p.USERDOC_FILE_TYP FILE_TYP, p.USERDOC_FILE_SER FILE_SER, p.USERDOC_FILE_NBR FILE_NBR,
       fp.PROC_TYP FILE_PROC_TYP, fp.PROC_NBR FILE_PROC_NBR,fp.STATUS_CODE FILE_STATUS_CODE
from  ipasprod.IP_DOC d
left join ipasprod.IP_PROC p on p.DOC_ORI = d.DOC_ORI and p.DOC_LOG = d.DOC_LOG and d.DOC_SER = p.DOC_SER and d.DOC_NBR = p.DOC_NBR
left join ipasprod.IP_PROC fp on fp.PROC_TYP = p.FILE_PROC_TYP and fp.PROC_NBR = p.FILE_PROC_NBR
