--liquibase formatted sql

--changeset ggeorgiev:284.1
DROP VIEW [EXT_CORE].[VW_ACTION_INDEX];

--changeset ggeorgiev:284.2
CREATE VIEW [EXT_CORE].[VW_ACTION_INDEX] AS
SELECT a.PROC_TYP, a.PROC_NBR, a.ACTION_NBR, ACTION_TYP, ACTION_DATE, NEW_STATUS_CODE, PRIOR_STATUS_CODE, PRIOR_STATUS_DATE, RESPONSIBLE_USER_ID, CAPTURE_USER_ID,
j.YEAR JOURNAL_YEAR, j.BULETIN JOURNAL_BULETIN,  j.SECT JOURNAL_SECT
from IPASPROD.IP_ACTION a
LEFT JOIN EXT_JOURNAL.VW_JOURNAL j on a.PROC_TYP = j.PROC_TYP and a.PROC_NBR = j.PROC_NBR and a.ACTION_NBR = j.ACTION_NBR;

