--liquibase formatted sql

--changeset mmurlev:301.1
IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.COLUMNS
  WHERE
    TABLE_NAME = 'IP_OFFIDOC_PUBLISHED_DECISION' AND COLUMN_NAME = 'DOC_NBR')
BEGIN
 alter table ext_Core.IP_OFFIDOC_PUBLISHED_DECISION
	add DOC_NBR integer
END;

--changeset mmurlev:301.2
IF NOT EXISTS (
  SELECT
    *
  FROM
    INFORMATION_SCHEMA.COLUMNS
  WHERE
    TABLE_NAME = 'IP_OFFIDOC_PUBLISHED_DECISION' AND COLUMN_NAME = 'OFFIDOC_TYP')
BEGIN
 alter table ext_Core.IP_OFFIDOC_PUBLISHED_DECISION
	add OFFIDOC_TYP varchar(8)
END;



