create table ipasprod.EXT_CF_SIGN_TYPE
(
	SIGN_TYPE varchar(10) not null
		primary key,
	SIGN_TYPE_NAME varchar(255)
);

INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('C', 'Комбинация от цветове');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('D', 'Словна');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('F', 'Образна');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('M', 'Комбинирана');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('S', 'Звукова');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('T', 'Триизмерна');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('P', 'Позиционна');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('A', 'Десен');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('U', 'Мултимедийна');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('H', 'Холограмна');
INSERT INTO IPASPROD.EXT_CF_SIGN_TYPE (SIGN_TYPE, SIGN_TYPE_NAME) VALUES ('E', 'Други');

