-- USERDOC APPLICANTS
INSERT INTO EXT_CORE.IP_USERDOC_PERSON (ROW_VERSION, DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, PERSON_NBR, ADDR_NBR, ROLE, NOTES)
SELECT 1 as ROW_NUMBER,
       u.DOC_ORI,
       u.DOC_LOG,
       u.DOC_SER,
       u.DOC_NBR,
       u.APPLICANT_PERSON_NBR as PERSON_NBR,
       u.APPLICANT_ADDR_NBR as ADDR_NBR,
       'APPLICANT' as ROLE,
       null as NOTES
FROM IPASPROD.IP_USERDOC u
         JOIN IPASPROD.IP_PERSON_ADDRESSES pa
              on pa.PERSON_NBR = u.APPLICANT_PERSON_NBR AND pa.ADDR_NBR = u.APPLICANT_ADDR_NBR
where u.APPLICANT_ADDR_NBR is not null
  AND u.APPLICANT_PERSON_NBR is not null


UPDATE
    IPASPROD.IP_USERDOC
SET APPLICANT_PERSON_NBR = NULL,
    APPLICANT_ADDR_NBR   = NULL
FROM IPASPROD.IP_USERDOC u
         LEFT JOIN IPASPROD.IP_PERSON_ADDRESSES pa
                   on pa.PERSON_NBR = u.APPLICANT_PERSON_NBR AND pa.ADDR_NBR = u.APPLICANT_ADDR_NBR
where u.APPLICANT_ADDR_NBR is not null
  AND u.APPLICANT_PERSON_NBR is not null
  and pa.PERSON_NBR is null

-- USERDOC GRANTEE
INSERT INTO EXT_CORE.IP_USERDOC_PERSON (ROW_VERSION, DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, PERSON_NBR, ADDR_NBR, ROLE, NOTES)
SELECT 1 as ROW_NUMBER,
       u.DOC_ORI,
       u.DOC_LOG,
       u.DOC_SER,
       u.DOC_NBR,
       u.GRANTEE_PERSON_NBR as PERSON_NBR,
       u.GRANTEE_ADDR_NBR as ADDR_NBR,
       'GRANTEE' as ROLE,
       null as NOTES
FROM IPASPROD.IP_USERDOC u
         JOIN IPASPROD.IP_PERSON_ADDRESSES pa
              on pa.PERSON_NBR = u.GRANTEE_PERSON_NBR AND pa.ADDR_NBR = u.GRANTEE_ADDR_NBR
where u.GRANTEE_ADDR_NBR is not null
  AND u.GRANTEE_PERSON_NBR is not null

-- USERDOC GRANTOR
INSERT INTO EXT_CORE.IP_USERDOC_PERSON (ROW_VERSION, DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, PERSON_NBR, ADDR_NBR, ROLE, NOTES)
SELECT 1 as ROW_NUMBER,
       u.DOC_ORI,
       u.DOC_LOG,
       u.DOC_SER,
       u.DOC_NBR,
       u.GRANTOR_PERSON_NBR as PERSON_NBR,
       u.GRANTOR_ADDR_NBR as ADDR_NBR,
       'GRANTOR' as ROLE,
       null as NOTES
FROM IPASPROD.IP_USERDOC u
         JOIN IPASPROD.IP_PERSON_ADDRESSES pa
              on pa.PERSON_NBR = u.GRANTOR_PERSON_NBR AND pa.ADDR_NBR = u.GRANTOR_ADDR_NBR
where u.GRANTOR_ADDR_NBR is not null
  AND u.GRANTOR_PERSON_NBR is not null

-- USERDOC PAYEE
INSERT INTO EXT_CORE.IP_USERDOC_PERSON (ROW_VERSION, DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, PERSON_NBR, ADDR_NBR, ROLE, NOTES)
SELECT 1 as ROW_NUMBER,
       u.DOC_ORI,
       u.DOC_LOG,
       u.DOC_SER,
       u.DOC_NBR,
       u.PAYEE_PERSON_NBR as PERSON_NBR,
       u.PAYEE_ADDR_NBR as ADDR_NBR,
       'PAYEE' as ROLE,
       null as NOTES
FROM IPASPROD.IP_USERDOC u
         JOIN IPASPROD.IP_PERSON_ADDRESSES pa
              on pa.PERSON_NBR = u.PAYEE_PERSON_NBR AND pa.ADDR_NBR = u.PAYEE_ADDR_NBR
where u.PAYEE_ADDR_NBR is not null
  AND u.PAYEE_PERSON_NBR is not null

-- USERDOC PAYER
INSERT INTO EXT_CORE.IP_USERDOC_PERSON (ROW_VERSION, DOC_ORI, DOC_LOG, DOC_SER, DOC_NBR, PERSON_NBR, ADDR_NBR, ROLE, NOTES)
SELECT 1 as ROW_NUMBER,
       u.DOC_ORI,
       u.DOC_LOG,
       u.DOC_SER,
       u.DOC_NBR,
       u.PAYER_PERSON_NBR as PERSON_NBR,
       u.PAYER_ADDR_NBR as ADDR_NBR,
       'PAYER' as ROLE,
       null as NOTES
FROM IPASPROD.IP_USERDOC u
         JOIN IPASPROD.IP_PERSON_ADDRESSES pa
              on pa.PERSON_NBR = u.PAYER_PERSON_NBR AND pa.ADDR_NBR = u.PAYER_ADDR_NBR
where u.PAYER_ADDR_NBR is not null
  AND u.PAYER_PERSON_NBR is not null


