INSERT INTO EXT_CORE.CF_USERDOC_UI_PANEL (PANEL) VALUES ('Persons');
INSERT INTO EXT_USER.CF_SECURITY_ROLES (ROLE_NAME, DESCRIPTION) VALUES ('userdoc.object-person-data','Вторични действия: Преглед на панел "Лица и контакти"');

INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL)
SELECT  u.USERDOC_TYP,
        'Persons'
FROM IPASPROD.CF_USERDOC_TYPE u


