create table EXT_CORE.CF_USERDOC_PERSON_ROLE
(
    ROLE varchar(50) not null
        constraint CF_USERDOC_PERSON_ROLES_pk
        primary key nonclustered,
)
;

INSERT INTO EXT_CORE.CF_USERDOC_PERSON_ROLE (ROLE) VALUES ('APPLICANT');
INSERT INTO EXT_CORE.CF_USERDOC_PERSON_ROLE (ROLE) VALUES ('PAYEE');
INSERT INTO EXT_CORE.CF_USERDOC_PERSON_ROLE (ROLE) VALUES ('PAYER');
INSERT INTO EXT_CORE.CF_USERDOC_PERSON_ROLE (ROLE) VALUES ('GRANTEE');
INSERT INTO EXT_CORE.CF_USERDOC_PERSON_ROLE (ROLE) VALUES ('GRANTOR');


