
create table EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL
(
    USERDOC_TYP varchar(7)  not null
        constraint CF_USERDOC_TYPE_TO_UI_PANEL_USERDOC_TYPE_USERDOC_TYP_fk
            references IPASPROD.CF_USERDOC_TYPE,
    PANEL       varchar(50) not null
        constraint CF_USERDOC_TYPE_TO_UI_PANEL_CF_USERDOC_UI_PANEL_PANEL_fk
            references EXT_CORE.CF_USERDOC_UI_PANEL,
    constraint CF_USERDOC_TYPE_TO_PANEL_pk
        primary key nonclustered (USERDOC_TYP, PANEL)
)
;

INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL)
SELECT  u.USERDOC_TYP,
        'UserdocTypeData'
FROM IPASPROD.CF_USERDOC_TYPE u

INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL)
SELECT  u.USERDOC_TYP,
        'UserdocMainData'
FROM IPASPROD.CF_USERDOC_TYPE u

INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_UI_PANEL (USERDOC_TYP, PANEL)
SELECT  u.USERDOC_TYP,
        'Process'
FROM IPASPROD.CF_USERDOC_TYPE u;


