--liquibase formatted sql

--changeset mnakova:356.1
create table EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON
(
    ID                  INT IDENTITY NOT NULL,
    APPL_TYP            VARCHAR(3),
    ACP_CHECK_REASON_ID INT,
    CONSTRAINT ACP_CHECK_REASON_FK
        FOREIGN KEY (ACP_CHECK_REASON_ID) references EXT_CORE.CF_ACP_CHECK_REASON (ID),
    CONSTRAINT CF_APP_TYPE_ACP_CHECK_REASON_UNIQ UNIQUE (APPL_TYP, ACP_CHECK_REASON_ID),
    CONSTRAINT CF_APP_TYPE_ACP_CHECK_REASON_PK
        PRIMARY KEY (ID)
)