--liquibase formatted sql

--changeset ggeorgiev:359.1 splitStatements:false
drop VIEW       [IPASPROD].[VW_FILE_REPRS];

--changeset ggeorgiev:359.2 splitStatements:false
CREATE VIEW       [IPASPROD].[VW_FILE_REPRS] ( ROW_VERSION, FILE_SEQ, FILE_TYP, FILE_SER, FILE_NBR, PERSON_NBR, ADDR_NBR,    REPRESENTATIVE_TYP, ATTORNEY_POWER_TERM, REAUTHORIZATION_RIGHT, AUTHORIZATION_CONDITION ) AS
SELECT      ROW_VERSION,      FILE_SEQ,      FILE_TYP,      FILE_SER,      FILE_NBR,      PERSON_NBR,      ADDR_NBR,      REPRESENTATIVE_TYP, ATTORNEY_POWER_TERM, REAUTHORIZATION_RIGHT, AUTHORIZATION_CONDITION  FROM      ip_mark_reprs    UNION
SELECT      ROW_VERSION,      FILE_SEQ,      FILE_TYP,      FILE_SER,      FILE_NBR,      PERSON_NBR,      ADDR_NBR,      REPRESENTATIVE_TYP, ATTORNEY_POWER_TERM, REAUTHORIZATION_RIGHT, AUTHORIZATION_CONDITION  FROM      ip_patent_reprs
