ALTER TABLE ext_Core.IP_USERDOC_ROOT_GROUNDS
DROP COLUMN MOTIVES;

ALTER TABLE ext_Core.IP_USERDOC_ROOT_GROUNDS
DROP COLUMN REGISTRATION_NBR;

ALTER TABLE ext_Core.IP_USERDOC_ROOT_GROUNDS
ADD MOTIVES varchar(4096);

ALTER TABLE ext_Core.IP_USERDOC_ROOT_GROUNDS
ADD REGISTRATION_NBR varchar(50);


