INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES ('ПИЗ', 'NEW_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES ('ПИЗ', 'OLD_OWNER');

INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES ('ПИР', 'NEW_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES ('ПИР', 'OLD_OWNER');


