INSERT INTO CF_GEO_COUNTRY (ROW_VERSION, COUNTRY_CODE, COUNTRY_NAME, NATIONALITY, IND_WIPO_STATISTICS, XML_DESIGNER)
VALUES(1,'QZ','Community Plant Variety Office (European Community) (CPVO)','N/A','N','<PARAMS></PARAMS>');

INSERT INTO CF_GEO_COUNTRY (ROW_VERSION, COUNTRY_CODE, COUNTRY_NAME, NATIONALITY, IND_WIPO_STATISTICS, XML_DESIGNER)
VALUES(1,'IB','International Bureau of the WIPO','N/A','N','<PARAMS></PARAMS>');

INSERT INTO CF_GEO_COUNTRY (ROW_VERSION, COUNTRY_CODE, COUNTRY_NAME, NATIONALITY, IND_WIPO_STATISTICS, XML_DESIGNER)
VALUES(1,'EU','European Union','European Union','N','<PARAMS></PARAMS>')


