--liquibase formatted sql

--changeset dveizov:344
INSERT INTO EXT_CORE.CF_USERDOC_PERSON_ROLE (ROLE, IND_TAKE_FROM_OWNER, NAME, NAME_EN)
VALUES ('REPRESENTATIVE_OF_THE_OWNER', null, N'Пълномощник на притежателя', 'Representative of the owner');

INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ОПО', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ЖРО', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИОРМ', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИОПН', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИППЛ', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИОСПЗ', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИЗРД', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИЗРПМ', 'REPRESENTATIVE_OF_THE_OWNER');
INSERT INTO EXT_CORE.CF_USERDOC_TYPE_TO_PERSON_ROLE (USERDOC_TYP, ROLE) VALUES (N'ИЗРM', 'REPRESENTATIVE_OF_THE_OWNER');

