--liquibase formatted sql

--changeset dveizov:346.1
ALTER TABLE EXT_CORE.CF_USERDOC_PERSON_ROLE
    ADD IND_ADDITIONAL_OFFIDOC_CORRESPONDENT character varying(1) default NULL;

--changeset dveizov:346.2
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET IND_ADDITIONAL_OFFIDOC_CORRESPONDENT = 'S' WHERE ROLE = 'REPRESENTATIVE_OF_THE_OWNER';

