--liquibase formatted sql

--changeset mnakova:363
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('ZMR_FULL_CESSATION_ACTION_TYPE', '3736');
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('ZMR_PARTIAL_CESSATION_ACTION_TYPE', '3738');
