--liquibase formatted sql

--changeset mnakova:361.1
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('ZMR_IRREGULARITY_LETTER_ACTION_TYPE', '3740');
INSERT INTO IPASPROD.EXT_CONFIG_PARAM (CONFIG_CODE, VALUE) VALUES ('ZTR_IRREGULARITY_LETTER_ACTION_TYPE', '3741');