--liquibase formatted sql

--changeset mnakova:360
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'ИСД', 10);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'ИСД', 11);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'МК', 1);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'МК', 2);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'ПОП', 10);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'ПРП', 11);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'СИГ', 4);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'СИГ', 5);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'СИГ', 6);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'СИГ', 7);
INSERT INTO EXT_CORE.CF_APP_TYPE_ACP_CHECK_REASON (APPL_TYP, ACP_CHECK_REASON_ID) VALUES (N'СИГ', 8);