--liquibase formatted sql

--changeset mmurlev:196.1
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS where CONSTRAINT_NAME = 'ACTION_TYPE_FK')
alter table EXT_JOURNAL.NODE_DEFINITION_SUB drop constraint ACTION_TYPE_FK;

--changeset mmurlev:196.2
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS where CONSTRAINT_NAME = 'USERDOC_ACTION_TYPE_FK')
alter table EXT_JOURNAL.NODE_DEFINITION_SUB drop constraint USERDOC_ACTION_TYPE_FK;

--changeset mmurlev:196.3
UPDATE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE set DOC_REGISTRATION_TYPE = 3 where id in (208,209)

--changeset mmurlev:196.4
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS where CONSTRAINT_NAME = 'IP_FILE_RELATIONSHIP_REL_TYP_FK')
alter table EXT_CORE.IP_FILE_RELATIONSHIP_EXTENDED drop constraint IP_FILE_RELATIONSHIP_REL_TYP_FK;


