--liquibase formatted sql

--changeset dveizov:190
INSERT INTO IPASPROD.CF_PERSON_ID_TYPE (ROW_VERSION, PERSON_ID_TYP, PERSON_ID_NAME, IND_GENERAL_ID, IND_INDIVIDUAL_ID) VALUES (1, N'LAST', null, null, null);
INSERT INTO IPASPROD.CF_PERSON_ID_TYPE (ROW_VERSION, PERSON_ID_TYP, PERSON_ID_NAME, IND_GENERAL_ID, IND_INDIVIDUAL_ID) VALUES (1, N'OLD', null, null, null);


