--liquibase formatted sql

--changeset dveizov:197
DROP INDEX CF_ABDOCS_DOCUMENT_TYPE_TYPE_uindex ON EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE;
ALTER TABLE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE DROP CONSTRAINT CF_ABDOCS_DOCUMENT_TYPE_pk;
ALTER TABLE EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE ADD CONSTRAINT CF_ABDOCS_DOCUMENT_TYPE_pk PRIMARY KEY (TYPE);
CREATE UNIQUE INDEX CF_ABDOCS_DOCUMENT_TYPE_ID_uindex ON EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE (ID);
EXEC sp_rename 'EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE.ID', ABDOCS_DOC_TYPE_ID, 'COLUMN';
