--liquibase formatted sql

--changeset mmurlev:195
INSERT INTO EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE (ID, TYPE, NAME, IPAS_OBJECT, DOC_REGISTRATION_TYPE) VALUES (208, N'I', N'Международна марка', N'MARK', 4);
INSERT INTO EXT_RECEPTION.CF_ABDOCS_DOCUMENT_TYPE (ID, TYPE, NAME, IPAS_OBJECT, DOC_REGISTRATION_TYPE) VALUES (209, N'R', N'Териториялно разширение', N'MARK', 4);

