//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for ClassDescriptionDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClassDescriptionDetailsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LanguageCode" type="{http://oami.europa.eu/trademark/goods-services/term-verification}EM_LanguageCodeType"/&gt;
 *         &lt;element name="OfficeCode" type="{http://oami.europa.eu/trademark/goods-services/term-verification}WIPOST3CodeType"/&gt;
 *         &lt;element name="InputTermList" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="SearchOnSublevel" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SearchInLegacy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="SearchFuzzy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ClassNumber" type="{http://oami.europa.eu/trademark/goods-services/term-verification}NiceClassNumberType" minOccurs="0"/&gt;
 *         &lt;element name="VerifiedTermsDetails" type="{http://oami.europa.eu/trademark/goods-services/term-verification}VerifiedTermsDetailsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClassDescriptionDetailsType", propOrder = {
    "languageCode",
    "officeCode",
    "inputTermList",
    "searchOnSublevel",
    "searchInLegacy",
    "searchFuzzy",
    "classNumber",
    "verifiedTermsDetails"
})
public class ClassDescriptionDetailsType {

    @XmlElement(name = "LanguageCode", required = true)
    @XmlSchemaType(name = "NMTOKEN")
    protected EMLanguageCodeType languageCode;
    @XmlElement(name = "OfficeCode", required = true)
    @XmlSchemaType(name = "NMTOKEN")
    protected WIPOST3CodeType officeCode;
    @XmlElement(name = "InputTermList", required = true)
    protected String inputTermList;
    @XmlElement(name = "SearchOnSublevel")
    protected Boolean searchOnSublevel;
    @XmlElement(name = "SearchInLegacy")
    protected Boolean searchInLegacy;
    @XmlElement(name = "SearchFuzzy")
    protected Boolean searchFuzzy;
    @XmlElement(name = "ClassNumber")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected Integer classNumber;
    @XmlElement(name = "VerifiedTermsDetails", required = true)
    protected VerifiedTermsDetailsType verifiedTermsDetails;

    /**
     * Gets the value of the languageCode property.
     * 
     * @return
     *     possible object is
     *     {@link EMLanguageCodeType }
     *     
     */
    public EMLanguageCodeType getLanguageCode() {
        return languageCode;
    }

    /**
     * Sets the value of the languageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link EMLanguageCodeType }
     *     
     */
    public void setLanguageCode(EMLanguageCodeType value) {
        this.languageCode = value;
    }

    /**
     * Gets the value of the officeCode property.
     * 
     * @return
     *     possible object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public WIPOST3CodeType getOfficeCode() {
        return officeCode;
    }

    /**
     * Sets the value of the officeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link WIPOST3CodeType }
     *     
     */
    public void setOfficeCode(WIPOST3CodeType value) {
        this.officeCode = value;
    }

    /**
     * Gets the value of the inputTermList property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputTermList() {
        return inputTermList;
    }

    /**
     * Sets the value of the inputTermList property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputTermList(String value) {
        this.inputTermList = value;
    }

    /**
     * Gets the value of the searchOnSublevel property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchOnSublevel() {
        return searchOnSublevel;
    }

    /**
     * Sets the value of the searchOnSublevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchOnSublevel(Boolean value) {
        this.searchOnSublevel = value;
    }

    /**
     * Gets the value of the searchInLegacy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchInLegacy() {
        return searchInLegacy;
    }

    /**
     * Sets the value of the searchInLegacy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchInLegacy(Boolean value) {
        this.searchInLegacy = value;
    }

    /**
     * Gets the value of the searchFuzzy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isSearchFuzzy() {
        return searchFuzzy;
    }

    /**
     * Sets the value of the searchFuzzy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSearchFuzzy(Boolean value) {
        this.searchFuzzy = value;
    }

    /**
     * Gets the value of the classNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getClassNumber() {
        return classNumber;
    }

    /**
     * Sets the value of the classNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setClassNumber(Integer value) {
        this.classNumber = value;
    }

    /**
     * Gets the value of the verifiedTermsDetails property.
     * 
     * @return
     *     possible object is
     *     {@link VerifiedTermsDetailsType }
     *     
     */
    public VerifiedTermsDetailsType getVerifiedTermsDetails() {
        return verifiedTermsDetails;
    }

    /**
     * Sets the value of the verifiedTermsDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerifiedTermsDetailsType }
     *     
     */
    public void setVerifiedTermsDetails(VerifiedTermsDetailsType value) {
        this.verifiedTermsDetails = value;
    }

}
