//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClassificationTermSourceType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClassificationTermSourceType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Rejection database"/&gt;
 *     &lt;enumeration value="Reference database"/&gt;
 *     &lt;enumeration value="Legacy database"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ClassificationTermSourceType")
@XmlEnum
public enum ClassificationTermSourceType {

    @XmlEnumValue("Rejection database")
    REJECTION_DATABASE("Rejection database"),
    @XmlEnumValue("Reference database")
    REFERENCE_DATABASE("Reference database"),
    @XmlEnumValue("Legacy database")
    LEGACY_DATABASE("Legacy database");
    private final String value;

    ClassificationTermSourceType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ClassificationTermSourceType fromValue(String v) {
        for (ClassificationTermSourceType c: ClassificationTermSourceType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
