//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * <p>Java class for MatchedTermType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchedTermType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TermSourceType" type="{http://oami.europa.eu/trademark/goods-services/term-verification}ClassificationTermSourceType"/&gt;
 *         &lt;element name="IsPartial" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="MatchClassType" type="{http://oami.europa.eu/trademark/goods-services/term-verification}MatchClassTypeType"/&gt;
 *         &lt;element name="MatchProximity" type="{http://oami.europa.eu/trademark/goods-services/term-verification}MatchProximityType"/&gt;
 *         &lt;element name="MatchedClassNumber" type="{http://oami.europa.eu/trademark/goods-services/term-verification}NiceClassNumberType"/&gt;
 *         &lt;element name="MatchedTermText" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Identifier" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *         &lt;element name="MatchedTermPositionInInputTermList" type="{http://oami.europa.eu/trademark/goods-services/term-verification}SubStringPositionType" minOccurs="0"/&gt;
 *         &lt;element name="MatchedTermPositionInInputTerm" type="{http://oami.europa.eu/trademark/goods-services/term-verification}SubStringPositionType" minOccurs="0"/&gt;
 *         &lt;element name="MatchRank" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="LegacyTermFrequency" type="{http://www.w3.org/2001/XMLSchema}nonNegativeInteger" minOccurs="0"/&gt;
 *         &lt;element name="LegacyTermFirstUseDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="LegacyTermLastUseDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="HarmoConcept" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MatchedTerminologySourceList" type="{http://oami.europa.eu/trademark/goods-services/term-verification}MatchedTerminologySourceList" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchedTermType", propOrder = {
    "termSourceType",
    "isPartial",
    "matchClassType",
    "matchProximity",
    "matchedClassNumber",
    "matchedTermText",
    "identifier",
    "matchedTermPositionInInputTermList",
    "matchedTermPositionInInputTerm",
    "matchRank",
    "legacyTermFrequency",
    "legacyTermFirstUseDate",
    "legacyTermLastUseDate",
    "harmoConcept",
    "matchedTerminologySourceList"
})
public class MatchedTermType {

    @XmlElement(name = "TermSourceType", required = true)
    @XmlSchemaType(name = "token")
    protected ClassificationTermSourceType termSourceType;
    @XmlElement(name = "IsPartial")
    protected Boolean isPartial;
    @XmlElement(name = "MatchClassType", required = true)
    @XmlSchemaType(name = "token")
    protected MatchClassTypeType matchClassType;
    @XmlElement(name = "MatchProximity", required = true)
    @XmlSchemaType(name = "token")
    protected MatchProximityType matchProximity;
    @XmlElement(name = "MatchedClassNumber")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected int matchedClassNumber;
    @XmlElement(name = "MatchedTermText", required = true)
    protected String matchedTermText;
    @XmlElement(name = "Identifier", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String identifier;
    @XmlElement(name = "MatchedTermPositionInInputTermList")
    protected SubStringPositionType matchedTermPositionInInputTermList;
    @XmlElement(name = "MatchedTermPositionInInputTerm")
    protected SubStringPositionType matchedTermPositionInInputTerm;
    @XmlElement(name = "MatchRank")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger matchRank;
    @XmlElement(name = "LegacyTermFrequency")
    @XmlSchemaType(name = "nonNegativeInteger")
    protected BigInteger legacyTermFrequency;
    @XmlElement(name = "LegacyTermFirstUseDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar legacyTermFirstUseDate;
    @XmlElement(name = "LegacyTermLastUseDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar legacyTermLastUseDate;
    @XmlElement(name = "HarmoConcept")
    protected String harmoConcept;
    @XmlElement(name = "MatchedTerminologySourceList")
    protected MatchedTerminologySourceList matchedTerminologySourceList;

    /**
     * Gets the value of the termSourceType property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationTermSourceType }
     *     
     */
    public ClassificationTermSourceType getTermSourceType() {
        return termSourceType;
    }

    /**
     * Sets the value of the termSourceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationTermSourceType }
     *     
     */
    public void setTermSourceType(ClassificationTermSourceType value) {
        this.termSourceType = value;
    }

    /**
     * Gets the value of the isPartial property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPartial() {
        return isPartial;
    }

    /**
     * Sets the value of the isPartial property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPartial(Boolean value) {
        this.isPartial = value;
    }

    /**
     * Gets the value of the matchClassType property.
     * 
     * @return
     *     possible object is
     *     {@link MatchClassTypeType }
     *     
     */
    public MatchClassTypeType getMatchClassType() {
        return matchClassType;
    }

    /**
     * Sets the value of the matchClassType property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchClassTypeType }
     *     
     */
    public void setMatchClassType(MatchClassTypeType value) {
        this.matchClassType = value;
    }

    /**
     * Gets the value of the matchProximity property.
     * 
     * @return
     *     possible object is
     *     {@link MatchProximityType }
     *     
     */
    public MatchProximityType getMatchProximity() {
        return matchProximity;
    }

    /**
     * Sets the value of the matchProximity property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchProximityType }
     *     
     */
    public void setMatchProximity(MatchProximityType value) {
        this.matchProximity = value;
    }

    /**
     * Gets the value of the matchedClassNumber property.
     * 
     */
    public int getMatchedClassNumber() {
        return matchedClassNumber;
    }

    /**
     * Sets the value of the matchedClassNumber property.
     * 
     */
    public void setMatchedClassNumber(int value) {
        this.matchedClassNumber = value;
    }

    /**
     * Gets the value of the matchedTermText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchedTermText() {
        return matchedTermText;
    }

    /**
     * Sets the value of the matchedTermText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchedTermText(String value) {
        this.matchedTermText = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the matchedTermPositionInInputTermList property.
     * 
     * @return
     *     possible object is
     *     {@link SubStringPositionType }
     *     
     */
    public SubStringPositionType getMatchedTermPositionInInputTermList() {
        return matchedTermPositionInInputTermList;
    }

    /**
     * Sets the value of the matchedTermPositionInInputTermList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubStringPositionType }
     *     
     */
    public void setMatchedTermPositionInInputTermList(SubStringPositionType value) {
        this.matchedTermPositionInInputTermList = value;
    }

    /**
     * Gets the value of the matchedTermPositionInInputTerm property.
     * 
     * @return
     *     possible object is
     *     {@link SubStringPositionType }
     *     
     */
    public SubStringPositionType getMatchedTermPositionInInputTerm() {
        return matchedTermPositionInInputTerm;
    }

    /**
     * Sets the value of the matchedTermPositionInInputTerm property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubStringPositionType }
     *     
     */
    public void setMatchedTermPositionInInputTerm(SubStringPositionType value) {
        this.matchedTermPositionInInputTerm = value;
    }

    /**
     * Gets the value of the matchRank property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMatchRank() {
        return matchRank;
    }

    /**
     * Sets the value of the matchRank property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMatchRank(BigInteger value) {
        this.matchRank = value;
    }

    /**
     * Gets the value of the legacyTermFrequency property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLegacyTermFrequency() {
        return legacyTermFrequency;
    }

    /**
     * Sets the value of the legacyTermFrequency property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLegacyTermFrequency(BigInteger value) {
        this.legacyTermFrequency = value;
    }

    /**
     * Gets the value of the legacyTermFirstUseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLegacyTermFirstUseDate() {
        return legacyTermFirstUseDate;
    }

    /**
     * Sets the value of the legacyTermFirstUseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLegacyTermFirstUseDate(XMLGregorianCalendar value) {
        this.legacyTermFirstUseDate = value;
    }

    /**
     * Gets the value of the legacyTermLastUseDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLegacyTermLastUseDate() {
        return legacyTermLastUseDate;
    }

    /**
     * Sets the value of the legacyTermLastUseDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLegacyTermLastUseDate(XMLGregorianCalendar value) {
        this.legacyTermLastUseDate = value;
    }

    /**
     * Gets the value of the harmoConcept property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHarmoConcept() {
        return harmoConcept;
    }

    /**
     * Sets the value of the harmoConcept property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHarmoConcept(String value) {
        this.harmoConcept = value;
    }

    /**
     * Gets the value of the matchedTerminologySourceList property.
     * 
     * @return
     *     possible object is
     *     {@link MatchedTerminologySourceList }
     *     
     */
    public MatchedTerminologySourceList getMatchedTerminologySourceList() {
        return matchedTerminologySourceList;
    }

    /**
     * Sets the value of the matchedTerminologySourceList property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchedTerminologySourceList }
     *     
     */
    public void setMatchedTerminologySourceList(MatchedTerminologySourceList value) {
        this.matchedTerminologySourceList = value;
    }

}
