//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MatchClassTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MatchClassTypeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="Same class"/&gt;
 *     &lt;enumeration value="Wrong class"/&gt;
 *     &lt;enumeration value="None"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "MatchClassTypeType")
@XmlEnum
public enum MatchClassTypeType {

    @XmlEnumValue("Same class")
    SAME_CLASS("Same class"),
    @XmlEnumValue("Wrong class")
    WRONG_CLASS("Wrong class"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    MatchClassTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MatchClassTypeType fromValue(String v) {
        for (MatchClassTypeType c: MatchClassTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
