//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bg.duosoft.ipas.integration.tmclass.verify.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Transaction_QNAME = new QName("http://oami.europa.eu/trademark/goods-services/term-verification", "Transaction");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bg.duosoft.ipas.integration.tmclass.verify.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TransactionDataType }
     * 
     */
    public TransactionDataType createTransactionDataType() {
        return new TransactionDataType();
    }

    /**
     * Create an instance of {@link TransactionBodyType }
     * 
     */
    public TransactionBodyType createTransactionBodyType() {
        return new TransactionBodyType();
    }

    /**
     * Create an instance of {@link TransactionHeaderType }
     * 
     */
    public TransactionHeaderType createTransactionHeaderType() {
        return new TransactionHeaderType();
    }

    /**
     * Create an instance of {@link TransactionType }
     * 
     */
    public TransactionType createTransactionType() {
        return new TransactionType();
    }

    /**
     * Create an instance of {@link VerifyListResponseType }
     * 
     */
    public VerifyListResponseType createVerifyListResponseType() {
        return new VerifyListResponseType();
    }

    /**
     * Create an instance of {@link GoodsServicesDetailsType }
     * 
     */
    public GoodsServicesDetailsType createGoodsServicesDetailsType() {
        return new GoodsServicesDetailsType();
    }

    /**
     * Create an instance of {@link ClassDescriptionDetailsType }
     * 
     */
    public ClassDescriptionDetailsType createClassDescriptionDetailsType() {
        return new ClassDescriptionDetailsType();
    }

    /**
     * Create an instance of {@link VerifiedTermsDetailsType }
     * 
     */
    public VerifiedTermsDetailsType createVerifiedTermsDetailsType() {
        return new VerifiedTermsDetailsType();
    }

    /**
     * Create an instance of {@link VerifiedTermType }
     * 
     */
    public VerifiedTermType createVerifiedTermType() {
        return new VerifiedTermType();
    }

    /**
     * Create an instance of {@link MatchedTermsType }
     * 
     */
    public MatchedTermsType createMatchedTermsType() {
        return new MatchedTermsType();
    }

    /**
     * Create an instance of {@link MatchedTerminologySourceList }
     * 
     */
    public MatchedTerminologySourceList createMatchedTerminologySourceList() {
        return new MatchedTerminologySourceList();
    }

    /**
     * Create an instance of {@link MatchedTermType }
     * 
     */
    public MatchedTermType createMatchedTermType() {
        return new MatchedTermType();
    }

    /**
     * Create an instance of {@link SubStringPositionType }
     * 
     */
    public SubStringPositionType createSubStringPositionType() {
        return new SubStringPositionType();
    }

    /**
     * Create an instance of {@link TextType }
     * 
     */
    public TextType createTextType() {
        return new TextType();
    }

    /**
     * Create an instance of {@link TaxonomyType }
     * 
     */
    public TaxonomyType createTaxonomyType() {
        return new TaxonomyType();
    }

    /**
     * Create an instance of {@link TransactionDataType.VerifyList }
     * 
     */
    public TransactionDataType.VerifyList createTransactionDataTypeVerifyList() {
        return new TransactionDataType.VerifyList();
    }

    /**
     * Create an instance of {@link TransactionBodyType.TransactionContentDetails }
     * 
     */
    public TransactionBodyType.TransactionContentDetails createTransactionBodyTypeTransactionContentDetails() {
        return new TransactionBodyType.TransactionContentDetails();
    }

    /**
     * Create an instance of {@link TransactionHeaderType.SenderDetails }
     * 
     */
    public TransactionHeaderType.SenderDetails createTransactionHeaderTypeSenderDetails() {
        return new TransactionHeaderType.SenderDetails();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TransactionType }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link TransactionType }{@code >}
     */
    @XmlElementDecl(namespace = "http://oami.europa.eu/trademark/goods-services/term-verification", name = "Transaction")
    public JAXBElement<TransactionType> createTransaction(TransactionType value) {
        return new JAXBElement<TransactionType>(_Transaction_QNAME, TransactionType.class, null, value);
    }

}
