//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://oami.europa.eu/trademark/goods-services/term-verification", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bg.duosoft.ipas.integration.tmclass.verify.model;
