//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TransactionDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionDataType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="VerifyList"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="VerifyListResponse" type="{http://oami.europa.eu/trademark/goods-services/term-verification}VerifyListResponseType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionDataType", propOrder = {
    "verifyList"
})
public class TransactionDataType {

    @XmlElement(name = "VerifyList", required = true)
    protected VerifyList verifyList;

    /**
     * Gets the value of the verifyList property.
     * 
     * @return
     *     possible object is
     *     {@link VerifyList }
     *     
     */
    public VerifyList getVerifyList() {
        return verifyList;
    }

    /**
     * Sets the value of the verifyList property.
     * 
     * @param value
     *     allowed object is
     *     {@link VerifyList }
     *     
     */
    public void setVerifyList(VerifyList value) {
        this.verifyList = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="VerifyListResponse" type="{http://oami.europa.eu/trademark/goods-services/term-verification}VerifyListResponseType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "verifyListResponse"
    })
    public static class VerifyList {

        @XmlElement(name = "VerifyListResponse", required = true)
        protected VerifyListResponseType verifyListResponse;

        /**
         * Gets the value of the verifyListResponse property.
         * 
         * @return
         *     possible object is
         *     {@link VerifyListResponseType }
         *     
         */
        public VerifyListResponseType getVerifyListResponse() {
            return verifyListResponse;
        }

        /**
         * Sets the value of the verifyListResponse property.
         * 
         * @param value
         *     allowed object is
         *     {@link VerifyListResponseType }
         *     
         */
        public void setVerifyListResponse(VerifyListResponseType value) {
            this.verifyListResponse = value;
        }

    }

}
