//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.*;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for TransactionBodyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TransactionBodyType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="TransactionContentDetails"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="TransactionIdentifier" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
 *                   &lt;element name="TransactionCode" type="{http://oami.europa.eu/trademark/goods-services/term-verification}TransactionCodeType"/&gt;
 *                   &lt;element name="TransactionData" type="{http://oami.europa.eu/trademark/goods-services/term-verification}TransactionDataType"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TransactionBodyType", propOrder = {
    "transactionContentDetails"
})
public class TransactionBodyType {

    @XmlElement(name = "TransactionContentDetails", required = true)
    protected TransactionContentDetails transactionContentDetails;

    /**
     * Gets the value of the transactionContentDetails property.
     * 
     * @return
     *     possible object is
     *     {@link TransactionContentDetails }
     *     
     */
    public TransactionContentDetails getTransactionContentDetails() {
        return transactionContentDetails;
    }

    /**
     * Sets the value of the transactionContentDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransactionContentDetails }
     *     
     */
    public void setTransactionContentDetails(TransactionContentDetails value) {
        this.transactionContentDetails = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="TransactionIdentifier" type="{http://www.w3.org/2001/XMLSchema}token"/&gt;
     *         &lt;element name="TransactionCode" type="{http://oami.europa.eu/trademark/goods-services/term-verification}TransactionCodeType"/&gt;
     *         &lt;element name="TransactionData" type="{http://oami.europa.eu/trademark/goods-services/term-verification}TransactionDataType"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "transactionIdentifier",
        "transactionCode",
        "transactionData"
    })
    public static class TransactionContentDetails {

        @XmlElement(name = "TransactionIdentifier", required = true)
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        @XmlSchemaType(name = "token")
        protected String transactionIdentifier;
        @XmlElement(name = "TransactionCode", required = true)
        @XmlSchemaType(name = "token")
        protected TransactionCodeType transactionCode;
        @XmlElement(name = "TransactionData", required = true)
        protected TransactionDataType transactionData;

        /**
         * Gets the value of the transactionIdentifier property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTransactionIdentifier() {
            return transactionIdentifier;
        }

        /**
         * Sets the value of the transactionIdentifier property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTransactionIdentifier(String value) {
            this.transactionIdentifier = value;
        }

        /**
         * Gets the value of the transactionCode property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionCodeType }
         *     
         */
        public TransactionCodeType getTransactionCode() {
            return transactionCode;
        }

        /**
         * Sets the value of the transactionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionCodeType }
         *     
         */
        public void setTransactionCode(TransactionCodeType value) {
            this.transactionCode = value;
        }

        /**
         * Gets the value of the transactionData property.
         * 
         * @return
         *     possible object is
         *     {@link TransactionDataType }
         *     
         */
        public TransactionDataType getTransactionData() {
            return transactionData;
        }

        /**
         * Sets the value of the transactionData property.
         * 
         * @param value
         *     allowed object is
         *     {@link TransactionDataType }
         *     
         */
        public void setTransactionData(TransactionDataType value) {
            this.transactionData = value;
        }

    }

}
