//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerifiedTermResultType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="VerifiedTermResultType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="OK"/&gt;
 *     &lt;enumeration value="Hint"/&gt;
 *     &lt;enumeration value="Not OK"/&gt;
 *     &lt;enumeration value="None"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "VerifiedTermResultType")
@XmlEnum
public enum VerifiedTermResultType {

    OK("OK"),
    @XmlEnumValue("Hint")
    HINT("Hint"),
    @XmlEnumValue("Not OK")
    NOT_OK("Not OK"),
    @XmlEnumValue("None")
    NONE("None");
    private final String value;

    VerifiedTermResultType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static VerifiedTermResultType fromValue(String v) {
        for (VerifiedTermResultType c: VerifiedTermResultType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
