//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for VerifyListResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="VerifyListResponseType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="GoodsServicesDetails" type="{http://oami.europa.eu/trademark/goods-services/term-verification}GoodsServicesDetailsType"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VerifyListResponseType", propOrder = {
    "goodsServicesDetails"
})
public class VerifyListResponseType {

    @XmlElement(name = "GoodsServicesDetails", required = true)
    protected GoodsServicesDetailsType goodsServicesDetails;

    /**
     * Gets the value of the goodsServicesDetails property.
     * 
     * @return
     *     possible object is
     *     {@link GoodsServicesDetailsType }
     *     
     */
    public GoodsServicesDetailsType getGoodsServicesDetails() {
        return goodsServicesDetails;
    }

    /**
     * Sets the value of the goodsServicesDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link GoodsServicesDetailsType }
     *     
     */
    public void setGoodsServicesDetails(GoodsServicesDetailsType value) {
        this.goodsServicesDetails = value;
    }

}
