//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.14 at 01:17:22 PM EET 
//


package bg.duosoft.ipas.integration.tmclass.verify.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WIPOST3CodeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WIPOST3CodeType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN"&gt;
 *     &lt;enumeration value="AD"/&gt;
 *     &lt;enumeration value="AE"/&gt;
 *     &lt;enumeration value="AF"/&gt;
 *     &lt;enumeration value="AG"/&gt;
 *     &lt;enumeration value="AI"/&gt;
 *     &lt;enumeration value="AL"/&gt;
 *     &lt;enumeration value="AM"/&gt;
 *     &lt;enumeration value="AN"/&gt;
 *     &lt;enumeration value="AO"/&gt;
 *     &lt;enumeration value="AP"/&gt;
 *     &lt;enumeration value="AR"/&gt;
 *     &lt;enumeration value="AT"/&gt;
 *     &lt;enumeration value="AU"/&gt;
 *     &lt;enumeration value="AW"/&gt;
 *     &lt;enumeration value="AZ"/&gt;
 *     &lt;enumeration value="BA"/&gt;
 *     &lt;enumeration value="BB"/&gt;
 *     &lt;enumeration value="BD"/&gt;
 *     &lt;enumeration value="BE"/&gt;
 *     &lt;enumeration value="BF"/&gt;
 *     &lt;enumeration value="BG"/&gt;
 *     &lt;enumeration value="BH"/&gt;
 *     &lt;enumeration value="BI"/&gt;
 *     &lt;enumeration value="BJ"/&gt;
 *     &lt;enumeration value="BM"/&gt;
 *     &lt;enumeration value="BN"/&gt;
 *     &lt;enumeration value="BO"/&gt;
 *     &lt;enumeration value="BR"/&gt;
 *     &lt;enumeration value="BS"/&gt;
 *     &lt;enumeration value="BT"/&gt;
 *     &lt;enumeration value="BV"/&gt;
 *     &lt;enumeration value="BW"/&gt;
 *     &lt;enumeration value="BX"/&gt;
 *     &lt;enumeration value="BY"/&gt;
 *     &lt;enumeration value="BZ"/&gt;
 *     &lt;enumeration value="CA"/&gt;
 *     &lt;enumeration value="CD"/&gt;
 *     &lt;enumeration value="CF"/&gt;
 *     &lt;enumeration value="CG"/&gt;
 *     &lt;enumeration value="CH"/&gt;
 *     &lt;enumeration value="CI"/&gt;
 *     &lt;enumeration value="CK"/&gt;
 *     &lt;enumeration value="CL"/&gt;
 *     &lt;enumeration value="CM"/&gt;
 *     &lt;enumeration value="CN"/&gt;
 *     &lt;enumeration value="CO"/&gt;
 *     &lt;enumeration value="CR"/&gt;
 *     &lt;enumeration value="CU"/&gt;
 *     &lt;enumeration value="CV"/&gt;
 *     &lt;enumeration value="CY"/&gt;
 *     &lt;enumeration value="CZ"/&gt;
 *     &lt;enumeration value="DE"/&gt;
 *     &lt;enumeration value="DJ"/&gt;
 *     &lt;enumeration value="DK"/&gt;
 *     &lt;enumeration value="DM"/&gt;
 *     &lt;enumeration value="DO"/&gt;
 *     &lt;enumeration value="DZ"/&gt;
 *     &lt;enumeration value="EA"/&gt;
 *     &lt;enumeration value="EC"/&gt;
 *     &lt;enumeration value="EE"/&gt;
 *     &lt;enumeration value="EG"/&gt;
 *     &lt;enumeration value="EH"/&gt;
 *     &lt;enumeration value="EM"/&gt;
 *     &lt;enumeration value="EP"/&gt;
 *     &lt;enumeration value="ER"/&gt;
 *     &lt;enumeration value="ES"/&gt;
 *     &lt;enumeration value="ET"/&gt;
 *     &lt;enumeration value="FI"/&gt;
 *     &lt;enumeration value="FJ"/&gt;
 *     &lt;enumeration value="FK"/&gt;
 *     &lt;enumeration value="FO"/&gt;
 *     &lt;enumeration value="FR"/&gt;
 *     &lt;enumeration value="GA"/&gt;
 *     &lt;enumeration value="GB"/&gt;
 *     &lt;enumeration value="GC"/&gt;
 *     &lt;enumeration value="GD"/&gt;
 *     &lt;enumeration value="GE"/&gt;
 *     &lt;enumeration value="GG"/&gt;
 *     &lt;enumeration value="GH"/&gt;
 *     &lt;enumeration value="GI"/&gt;
 *     &lt;enumeration value="GL"/&gt;
 *     &lt;enumeration value="GM"/&gt;
 *     &lt;enumeration value="GN"/&gt;
 *     &lt;enumeration value="GQ"/&gt;
 *     &lt;enumeration value="GR"/&gt;
 *     &lt;enumeration value="GS"/&gt;
 *     &lt;enumeration value="GT"/&gt;
 *     &lt;enumeration value="GW"/&gt;
 *     &lt;enumeration value="GY"/&gt;
 *     &lt;enumeration value="HK"/&gt;
 *     &lt;enumeration value="HN"/&gt;
 *     &lt;enumeration value="HR"/&gt;
 *     &lt;enumeration value="HT"/&gt;
 *     &lt;enumeration value="HU"/&gt;
 *     &lt;enumeration value="IB"/&gt;
 *     &lt;enumeration value="ID"/&gt;
 *     &lt;enumeration value="IE"/&gt;
 *     &lt;enumeration value="IL"/&gt;
 *     &lt;enumeration value="IM"/&gt;
 *     &lt;enumeration value="IN"/&gt;
 *     &lt;enumeration value="IQ"/&gt;
 *     &lt;enumeration value="IR"/&gt;
 *     &lt;enumeration value="IS"/&gt;
 *     &lt;enumeration value="IT"/&gt;
 *     &lt;enumeration value="JE"/&gt;
 *     &lt;enumeration value="JM"/&gt;
 *     &lt;enumeration value="JO"/&gt;
 *     &lt;enumeration value="JP"/&gt;
 *     &lt;enumeration value="KE"/&gt;
 *     &lt;enumeration value="KG"/&gt;
 *     &lt;enumeration value="KH"/&gt;
 *     &lt;enumeration value="KI"/&gt;
 *     &lt;enumeration value="KM"/&gt;
 *     &lt;enumeration value="KN"/&gt;
 *     &lt;enumeration value="KP"/&gt;
 *     &lt;enumeration value="KR"/&gt;
 *     &lt;enumeration value="KW"/&gt;
 *     &lt;enumeration value="KY"/&gt;
 *     &lt;enumeration value="KZ"/&gt;
 *     &lt;enumeration value="LA"/&gt;
 *     &lt;enumeration value="LB"/&gt;
 *     &lt;enumeration value="LC"/&gt;
 *     &lt;enumeration value="LI"/&gt;
 *     &lt;enumeration value="LK"/&gt;
 *     &lt;enumeration value="LR"/&gt;
 *     &lt;enumeration value="LS"/&gt;
 *     &lt;enumeration value="LT"/&gt;
 *     &lt;enumeration value="LU"/&gt;
 *     &lt;enumeration value="LV"/&gt;
 *     &lt;enumeration value="LY"/&gt;
 *     &lt;enumeration value="MA"/&gt;
 *     &lt;enumeration value="MC"/&gt;
 *     &lt;enumeration value="MD"/&gt;
 *     &lt;enumeration value="ME"/&gt;
 *     &lt;enumeration value="MG"/&gt;
 *     &lt;enumeration value="MK"/&gt;
 *     &lt;enumeration value="ML"/&gt;
 *     &lt;enumeration value="MM"/&gt;
 *     &lt;enumeration value="MN"/&gt;
 *     &lt;enumeration value="MO"/&gt;
 *     &lt;enumeration value="MP"/&gt;
 *     &lt;enumeration value="MR"/&gt;
 *     &lt;enumeration value="MS"/&gt;
 *     &lt;enumeration value="MT"/&gt;
 *     &lt;enumeration value="MU"/&gt;
 *     &lt;enumeration value="MV"/&gt;
 *     &lt;enumeration value="MW"/&gt;
 *     &lt;enumeration value="MX"/&gt;
 *     &lt;enumeration value="MY"/&gt;
 *     &lt;enumeration value="MZ"/&gt;
 *     &lt;enumeration value="NA"/&gt;
 *     &lt;enumeration value="NE"/&gt;
 *     &lt;enumeration value="NG"/&gt;
 *     &lt;enumeration value="NI"/&gt;
 *     &lt;enumeration value="NL"/&gt;
 *     &lt;enumeration value="NO"/&gt;
 *     &lt;enumeration value="NP"/&gt;
 *     &lt;enumeration value="NR"/&gt;
 *     &lt;enumeration value="NZ"/&gt;
 *     &lt;enumeration value="OA"/&gt;
 *     &lt;enumeration value="OM"/&gt;
 *     &lt;enumeration value="PA"/&gt;
 *     &lt;enumeration value="PE"/&gt;
 *     &lt;enumeration value="PG"/&gt;
 *     &lt;enumeration value="PH"/&gt;
 *     &lt;enumeration value="PK"/&gt;
 *     &lt;enumeration value="PL"/&gt;
 *     &lt;enumeration value="PT"/&gt;
 *     &lt;enumeration value="PW"/&gt;
 *     &lt;enumeration value="PY"/&gt;
 *     &lt;enumeration value="QA"/&gt;
 *     &lt;enumeration value="QZ"/&gt;
 *     &lt;enumeration value="RO"/&gt;
 *     &lt;enumeration value="RS"/&gt;
 *     &lt;enumeration value="RU"/&gt;
 *     &lt;enumeration value="RW"/&gt;
 *     &lt;enumeration value="SA"/&gt;
 *     &lt;enumeration value="SB"/&gt;
 *     &lt;enumeration value="SC"/&gt;
 *     &lt;enumeration value="SD"/&gt;
 *     &lt;enumeration value="SE"/&gt;
 *     &lt;enumeration value="SG"/&gt;
 *     &lt;enumeration value="SH"/&gt;
 *     &lt;enumeration value="SI"/&gt;
 *     &lt;enumeration value="SK"/&gt;
 *     &lt;enumeration value="SL"/&gt;
 *     &lt;enumeration value="SM"/&gt;
 *     &lt;enumeration value="SN"/&gt;
 *     &lt;enumeration value="SO"/&gt;
 *     &lt;enumeration value="SR"/&gt;
 *     &lt;enumeration value="ST"/&gt;
 *     &lt;enumeration value="SV"/&gt;
 *     &lt;enumeration value="SY"/&gt;
 *     &lt;enumeration value="SZ"/&gt;
 *     &lt;enumeration value="TC"/&gt;
 *     &lt;enumeration value="TD"/&gt;
 *     &lt;enumeration value="TG"/&gt;
 *     &lt;enumeration value="TH"/&gt;
 *     &lt;enumeration value="TJ"/&gt;
 *     &lt;enumeration value="TL"/&gt;
 *     &lt;enumeration value="TM"/&gt;
 *     &lt;enumeration value="TN"/&gt;
 *     &lt;enumeration value="TO"/&gt;
 *     &lt;enumeration value="TR"/&gt;
 *     &lt;enumeration value="TT"/&gt;
 *     &lt;enumeration value="TV"/&gt;
 *     &lt;enumeration value="TW"/&gt;
 *     &lt;enumeration value="TZ"/&gt;
 *     &lt;enumeration value="UA"/&gt;
 *     &lt;enumeration value="UG"/&gt;
 *     &lt;enumeration value="US"/&gt;
 *     &lt;enumeration value="UY"/&gt;
 *     &lt;enumeration value="UZ"/&gt;
 *     &lt;enumeration value="VA"/&gt;
 *     &lt;enumeration value="VC"/&gt;
 *     &lt;enumeration value="VE"/&gt;
 *     &lt;enumeration value="VG"/&gt;
 *     &lt;enumeration value="VN"/&gt;
 *     &lt;enumeration value="VU"/&gt;
 *     &lt;enumeration value="WO"/&gt;
 *     &lt;enumeration value="WS"/&gt;
 *     &lt;enumeration value="XN"/&gt;
 *     &lt;enumeration value="YE"/&gt;
 *     &lt;enumeration value="ZA"/&gt;
 *     &lt;enumeration value="ZM"/&gt;
 *     &lt;enumeration value="ZW"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "WIPOST3CodeType")
@XmlEnum
public enum WIPOST3CodeType {


    /**
     * Andorra
     * 
     */
    AD,

    /**
     * United Arab Emirates
     * 
     */
    AE,

    /**
     * Afghanistan
     * 
     */
    AF,

    /**
     * Antigua And Barbuda
     * 
     */
    AG,

    /**
     * Anguilla
     * 
     */
    AI,

    /**
     * Albania
     * 
     */
    AL,

    /**
     * Armenia
     * 
     */
    AM,

    /**
     * Netherlands Antilles
     * 
     */
    AN,

    /**
     * Angola
     * 
     */
    AO,

    /**
     * African Regional Industrial Property Organization (ARIPO)
     * 
     */
    AP,

    /**
     * Argentina
     * 
     */
    AR,

    /**
     * Austria
     * 
     */
    AT,

    /**
     * Australia
     * 
     */
    AU,

    /**
     * Aruba
     * 
     */
    AW,

    /**
     * Azerbaijan
     * 
     */
    AZ,

    /**
     * Bosnia and Herzegovina
     * 
     */
    BA,

    /**
     * Barbados
     * 
     */
    BB,

    /**
     * Bangladesh
     * 
     */
    BD,

    /**
     * Belgium
     * 
     */
    BE,

    /**
     * Burkina Faso
     * 
     */
    BF,

    /**
     * Bulgaria
     * 
     */
    BG,

    /**
     * Bahrain
     * 
     */
    BH,

    /**
     * Burundi
     * 
     */
    BI,

    /**
     * Benin
     * 
     */
    BJ,

    /**
     * Bermuda
     * 
     */
    BM,

    /**
     * Brunei Darussalam
     * 
     */
    BN,

    /**
     * Bolivia
     * 
     */
    BO,

    /**
     * Brazil
     * 
     */
    BR,

    /**
     * Bahamas
     * 
     */
    BS,

    /**
     * Bhutan
     * 
     */
    BT,

    /**
     * Bouvet Island
     * 
     */
    BV,

    /**
     * Botswana
     * 
     */
    BW,

    /**
     * Benelux Office for Intellectual Property (BOIP)
     * 
     */
    BX,

    /**
     * Belarus
     * 
     */
    BY,

    /**
     * Belize
     * 
     */
    BZ,

    /**
     * Canada
     * 
     */
    CA,

    /**
     * Democratic Republic of the Congo
     * 
     */
    CD,

    /**
     * Central African Republic
     * 
     */
    CF,

    /**
     * Congo
     * 
     */
    CG,

    /**
     * Switzerland
     * 
     */
    CH,

    /**
     * Cote D'Ivoire
     * 
     */
    CI,

    /**
     * Cook Islands
     * 
     */
    CK,

    /**
     * Chile
     * 
     */
    CL,

    /**
     * Cameroon
     * 
     */
    CM,

    /**
     * China
     * 
     */
    CN,

    /**
     * Colombia
     * 
     */
    CO,

    /**
     * Costa Rica
     * 
     */
    CR,

    /**
     * Cuba
     * 
     */
    CU,

    /**
     * Cape Verde
     * 
     */
    CV,

    /**
     * Cyprus
     * 
     */
    CY,

    /**
     * Czech Republic
     * 
     */
    CZ,

    /**
     * Germany
     * 
     */
    DE,

    /**
     * Djibouti
     * 
     */
    DJ,

    /**
     * Denmark
     * 
     */
    DK,

    /**
     * Dominica
     * 
     */
    DM,

    /**
     * Dominican Republic
     * 
     */
    DO,

    /**
     * Algeria
     * 
     */
    DZ,

    /**
     * Eurasian Patent Organization (EAPO)
     * 
     */
    EA,

    /**
     * Ecuador
     * 
     */
    EC,

    /**
     * Estonia
     * 
     */
    EE,

    /**
     * Egypt
     * 
     */
    EG,

    /**
     * Western Sahara
     * 
     */
    EH,

    /**
     * Office for Harmonization in the Internal Market (Trademarks and Designs) (OHIM)
     * 
     */
    EM,

    /**
     * European Patent Office (EPO)
     * 
     */
    EP,

    /**
     * Eritrea
     * 
     */
    ER,

    /**
     * Spain
     * 
     */
    ES,

    /**
     * Ethiopia
     * 
     */
    ET,

    /**
     * Finland
     * 
     */
    FI,

    /**
     * Fiji
     * 
     */
    FJ,

    /**
     * Falkland Islands (Malvinas)
     * 
     */
    FK,

    /**
     * Faroe Islands
     * 
     */
    FO,

    /**
     * France
     * 
     */
    FR,

    /**
     * Gabon
     * 
     */
    GA,

    /**
     * United Kingdom
     * 
     */
    GB,

    /**
     * Patent Office of the Cooperation Council for the Arab States of the Gulf (GCC)
     * 
     */
    GC,

    /**
     * Grenada
     * 
     */
    GD,

    /**
     * Georgia
     * 
     */
    GE,

    /**
     * Guernsey
     * 
     */
    GG,

    /**
     * Ghana
     * 
     */
    GH,

    /**
     * Gibraltar
     * 
     */
    GI,

    /**
     * Greenland
     * 
     */
    GL,

    /**
     * Gambia
     * 
     */
    GM,

    /**
     * Guinea
     * 
     */
    GN,

    /**
     * Equatorial Guinea
     * 
     */
    GQ,

    /**
     * Greece
     * 
     */
    GR,

    /**
     * South Georgia and South Sandwich Islands
     * 
     */
    GS,

    /**
     * Guatemala
     * 
     */
    GT,

    /**
     * Guinea-Bissau
     * 
     */
    GW,

    /**
     * Guyana
     * 
     */
    GY,

    /**
     * The Hong Kong Special Administration Region of the People's Republic of China
     * 
     */
    HK,

    /**
     * Honduras
     * 
     */
    HN,

    /**
     * Croatia
     * 
     */
    HR,

    /**
     * Haiti
     * 
     */
    HT,

    /**
     * Hungary
     * 
     */
    HU,

    /**
     * International Bureau of the World Intellectual Property Organization (WIPO)
     * 
     */
    IB,

    /**
     * Indonesia
     * 
     */
    ID,

    /**
     * Ireland
     * 
     */
    IE,

    /**
     * Israel
     * 
     */
    IL,

    /**
     * Isle of Man
     * 
     */
    IM,

    /**
     * India
     * 
     */
    IN,

    /**
     * Iraq
     * 
     */
    IQ,

    /**
     * Iran (Islamic Republic of)
     * 
     */
    IR,

    /**
     * Iceland
     * 
     */
    IS,

    /**
     * Italy
     * 
     */
    IT,

    /**
     * Jersey
     * 
     */
    JE,

    /**
     * Jamaica
     * 
     */
    JM,

    /**
     * Jordan
     * 
     */
    JO,

    /**
     * Japan
     * 
     */
    JP,

    /**
     * Kenya
     * 
     */
    KE,

    /**
     * Kyrgyzstan
     * 
     */
    KG,

    /**
     * Cambodia
     * 
     */
    KH,

    /**
     * Kiribati
     * 
     */
    KI,

    /**
     * Comoros
     * 
     */
    KM,

    /**
     * Saint Kitts and Nevis
     * 
     */
    KN,

    /**
     * Democratic People's Republic of Korea
     * 
     */
    KP,

    /**
     * Republic of Korea
     * 
     */
    KR,

    /**
     * Kuwait
     * 
     */
    KW,

    /**
     * Cayman Islands
     * 
     */
    KY,

    /**
     * Kazakhstan
     * 
     */
    KZ,

    /**
     * Lao People's Democratic Republic
     * 
     */
    LA,

    /**
     * Lebanon
     * 
     */
    LB,

    /**
     * Saint Lucia
     * 
     */
    LC,

    /**
     * Liechtenstein
     * 
     */
    LI,

    /**
     * Sri Lanka
     * 
     */
    LK,

    /**
     * Liberia
     * 
     */
    LR,

    /**
     * Lesotho
     * 
     */
    LS,

    /**
     * Lithuania
     * 
     */
    LT,

    /**
     * Luxembourg
     * 
     */
    LU,

    /**
     * Latvia
     * 
     */
    LV,

    /**
     * Libyan Arab Jamahiriya
     * 
     */
    LY,

    /**
     * Morocco
     * 
     */
    MA,

    /**
     * Monaco
     * 
     */
    MC,

    /**
     * Republic of Moldova
     * 
     */
    MD,

    /**
     * Montenegro
     * 
     */
    ME,

    /**
     * Madagascar
     * 
     */
    MG,

    /**
     * The former Yugoslav Republic of Macedonia
     * 
     */
    MK,

    /**
     * Mali
     * 
     */
    ML,

    /**
     * Myanmar
     * 
     */
    MM,

    /**
     * Mongolia
     * 
     */
    MN,

    /**
     * Macau
     * 
     */
    MO,

    /**
     * Northern Mariana Islands
     * 
     */
    MP,

    /**
     * Mauritania
     * 
     */
    MR,

    /**
     * Montserrat
     * 
     */
    MS,

    /**
     * Malta
     * 
     */
    MT,

    /**
     * Mauritius
     * 
     */
    MU,

    /**
     * Maldives
     * 
     */
    MV,

    /**
     * Malawi
     * 
     */
    MW,

    /**
     * Mexico
     * 
     */
    MX,

    /**
     * Malaysia
     * 
     */
    MY,

    /**
     * Mozambique
     * 
     */
    MZ,

    /**
     * Namibia
     * 
     */
    NA,

    /**
     * Niger
     * 
     */
    NE,

    /**
     * Nigeria
     * 
     */
    NG,

    /**
     * Nicaragua
     * 
     */
    NI,

    /**
     * Netherlands
     * 
     */
    NL,

    /**
     * Norway
     * 
     */
    NO,

    /**
     * Nepal
     * 
     */
    NP,

    /**
     * Nauru
     * 
     */
    NR,

    /**
     * New Zealand
     * 
     */
    NZ,

    /**
     * African Intellectual Property Organization (OAPI)
     * 
     */
    OA,

    /**
     * Oman
     * 
     */
    OM,

    /**
     * Panama
     * 
     */
    PA,

    /**
     * Peru
     * 
     */
    PE,

    /**
     * Papua New Guinea
     * 
     */
    PG,

    /**
     * Philippines
     * 
     */
    PH,

    /**
     * Pakistan
     * 
     */
    PK,

    /**
     * Poland
     * 
     */
    PL,

    /**
     * Portugal
     * 
     */
    PT,

    /**
     * Palau
     * 
     */
    PW,

    /**
     * Paraguay
     * 
     */
    PY,

    /**
     * Qatar
     * 
     */
    QA,

    /**
     * Community Plant Variety Office (European Community) (CPVO)
     * 
     */
    QZ,

    /**
     * Romania
     * 
     */
    RO,

    /**
     * Serbia
     * 
     */
    RS,

    /**
     * Russian Federation
     * 
     */
    RU,

    /**
     * Rwanda
     * 
     */
    RW,

    /**
     * Saudi Arabia
     * 
     */
    SA,

    /**
     * Solomon Islands
     * 
     */
    SB,

    /**
     * Seychelles
     * 
     */
    SC,

    /**
     * Sudan
     * 
     */
    SD,

    /**
     * Sweden
     * 
     */
    SE,

    /**
     * Singapore
     * 
     */
    SG,

    /**
     * Saint Helena
     * 
     */
    SH,

    /**
     * Slovenia
     * 
     */
    SI,

    /**
     * Slovakia
     * 
     */
    SK,

    /**
     * Sierra Leone
     * 
     */
    SL,

    /**
     * San Marino
     * 
     */
    SM,

    /**
     * Senegal
     * 
     */
    SN,

    /**
     * Somalia
     * 
     */
    SO,

    /**
     * Suriname
     * 
     */
    SR,

    /**
     * Sao Tome and Principe
     * 
     */
    ST,

    /**
     * El Salvador
     * 
     */
    SV,

    /**
     * Syrian Arab Republic
     * 
     */
    SY,

    /**
     * Swaziland
     * 
     */
    SZ,

    /**
     * Turks and Caicos Islands
     * 
     */
    TC,

    /**
     * Chad
     * 
     */
    TD,

    /**
     * Togo
     * 
     */
    TG,

    /**
     * Thailand
     * 
     */
    TH,

    /**
     * Tajikistan
     * 
     */
    TJ,

    /**
     * Timor-Leste
     * 
     */
    TL,

    /**
     * Turkmenistan
     * 
     */
    TM,

    /**
     * Tunisia
     * 
     */
    TN,

    /**
     * Tonga
     * 
     */
    TO,

    /**
     * Turkey
     * 
     */
    TR,

    /**
     * Trinidad and Tobago
     * 
     */
    TT,

    /**
     * Tuvalu
     * 
     */
    TV,

    /**
     * Taiwan, Province of China
     * 
     */
    TW,

    /**
     * United Republic of Tanzania
     * 
     */
    TZ,

    /**
     * Ukraine
     * 
     */
    UA,

    /**
     * Uganda
     * 
     */
    UG,

    /**
     * United States of America
     * 
     */
    US,

    /**
     * Uruguay
     * 
     */
    UY,

    /**
     * Uzbekistan
     * 
     */
    UZ,

    /**
     * Holy See
     * 
     */
    VA,

    /**
     * Saint Vincent and the Grenadines
     * 
     */
    VC,

    /**
     * Venezuela
     * 
     */
    VE,

    /**
     * Virgin Islands (British)
     * 
     */
    VG,

    /**
     * Viet Nam
     * 
     */
    VN,

    /**
     * Vanuatu
     * 
     */
    VU,

    /**
     * World Intellectual Property Organization (WIPO) (International Bureau of)
     * 
     */
    WO,

    /**
     * Samoa
     * 
     */
    WS,

    /**
     * Nordic Patent Institute (NPI)
     * 
     */
    XN,

    /**
     * Yemen
     * 
     */
    YE,

    /**
     * South Africa
     * 
     */
    ZA,

    /**
     * Zambia
     * 
     */
    ZM,

    /**
     * Zimbabwe
     * 
     */
    ZW;

    public String value() {
        return name();
    }

    public static WIPOST3CodeType fromValue(String v) {
        return valueOf(v);
    }

}
