--liquibase formatted sql

--changeset dveizov:227
INSERT INTO EXT_RECEPTION.CF_SUBMISSION_TYPE (ID, NAME, NAME_EN) VALUES (7, 'Електронно', 'Internet');
UPDATE EXT_RECEPTION.RECEPTION_REQUEST SET SUBMISSION_TYPE = 7 WHERE SUBMISSION_TYPE = 0;
UPDATE EXT_RECEPTION.RECEPTION_USERDOC_REQUEST SET SUBMISSION_TYPE = 7 WHERE SUBMISSION_TYPE = 0;
DELETE FROM EXT_RECEPTION.CF_SUBMISSION_TYPE where ID = 0;