--liquibase formatted sql

--changeset svtonev:226.1
IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS where CONSTRAINT_NAME = 'IP_USERDOC_APPROVED_NICE_CLASSES_CF_CLASS_NICE_FK')
alter table EXT_CORE.IP_USERDOC_APPROVED_NICE_CLASSES drop constraint IP_USERDOC_APPROVED_NICE_CLASSES_CF_CLASS_NICE_FK;

IF EXISTS ( SELECT * FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS where CONSTRAINT_NAME = 'EXTENDED_IP_MARK_NICE_CLASSES_FK')
alter table EXT_CORE.EXTENDED_IP_MARK_NICE_CLASSES drop constraint EXTENDED_IP_MARK_NICE_CLASSES_FK;