--liquibase formatted sql

--changeset vnikolov:136
INSERT INTO [EXT_CORE].[PLANT] (
      [FILE_SEQ]
      ,[FILE_TYP]
      ,[FILE_SER]
      ,[FILE_NBR]
      ,[PLANT_NUMENCLATURE_ID]
      ,[PROPOSED_DENOMINATION]
      ,[PROPOSED_DENOMINATION_ENG]
      ,[PUBL_DENOMINATION]
      ,[PUBL_DENOMINATION_ENG]
      ,[APPR_DENOMINATION]
      ,[APPR_DENOMINATION_ENG]
      ,[REJ_DENOMINATION]
      ,[REJ_DENOMINATION_ENG]
      ,[FEATURES]
      ,[STABILITY]
      ,[TESTING]
	  )
SELECT
      pt.FILE_SEQ
      ,pt.FILE_TYP
      ,pt.FILE_SER
      ,pt.FILE_NBR
      ,CAST(PARSENAME(ao.OPTION_NBR, 1) AS int)		AS ID                      -- int
      ,CAST(ac1.NOTES1 as varchar(255))				AS PROPOSED_DENOMINATION
      ,ac1.NOTES2									AS PROPOSED_DENOMINATION_ENG
      ,ac2.NOTES1									AS PUBL_DENOMINATION
      ,ac2.NOTES2									AS PUBL_DENOMINATION_ENG
      ,ac3.NOTES1									AS APPR_DENOMINATION
      ,ac3.NOTES2									AS APPR_DENOMINATION_ENG
      ,ac4.NOTES1									AS REJ_DENOMINATION
      ,ac4.NOTES2									AS REJ_DENOMINATION_ENG
      ,pt.EXAM_IPC_USED								AS FEATURES
      ,pt.EXAM_KEYWORDS_USED						AS STABILITY
      ,pt.EXAM_RESULT								AS TESTING
  FROM [IPASPROD].[IP_PATENT] pt
      LEFT JOIN [IPASPROD].[IP_PROC] p ON pt.FILE_NBR = p.FILE_NBR AND pt.FILE_SEQ = p.FILE_SEQ AND pt.FILE_SER = p.FILE_SER AND pt.FILE_TYP = p.FILE_TYP
      LEFT JOIN [IPASPROD].[IP_ACTION] ac ON p.PROC_NBR = ac.PROC_NBR AND p.PROC_TYP = ac.PROC_TYP AND ( ac.ACTION_TYP = '644' OR ac.ACTION_TYP = '645' OR ac.ACTION_TYP = '1220' )
      LEFT JOIN [IPASPROD].[IP_ACTION_OPTIONS] ao ON ac.PROC_TYP = ao.PROC_TYP AND ac.PROC_NBR = ao.PROC_NBR AND ac.ACTION_NBR = ao.ACTION_NBR

      LEFT JOIN [IPASPROD].[IP_ACTION] ac1 ON p.PROC_NBR = ac1.PROC_NBR AND p.PROC_TYP = ac1.PROC_TYP AND ac1.ACTION_TYP = '057'
      LEFT JOIN [IPASPROD].[IP_ACTION] ac2 ON p.PROC_NBR = ac2.PROC_NBR AND p.PROC_TYP = ac2.PROC_TYP AND ac2.ACTION_TYP = '058'
      LEFT JOIN [IPASPROD].[IP_ACTION] ac3 ON p.PROC_NBR = ac3.PROC_NBR AND p.PROC_TYP = ac3.PROC_TYP AND ac3.ACTION_TYP = '059'
      LEFT JOIN [IPASPROD].[IP_ACTION] ac4 ON p.PROC_NBR = ac4.PROC_NBR AND p.PROC_TYP = ac4.PROC_TYP AND ac4.ACTION_TYP = '060'
  WHERE pt.FILE_TYP = 'С'
  ORDER BY pt.FILE_SEQ, pt.FILE_TYP, pt.FILE_SER, pt.FILE_NBR;