--liquibase formatted sql

--changeset ggeorgiev:141.1
ALTER TABLE EXT_RECEPTION.CF_RECEPTION_TYPE ADD APPL_TYP varchar(3);

--changeset ggeorgiev:141.2
UPDATE EXT_RECEPTION.CF_RECEPTION_TYPE set APPL_TYP = (SELECT atp.APPL_TYP FROM CF_APPLICATION_TYPE atp WHERE atp.FILE_TYP = FILE_TYPE ) WHERE FILE_TYPE NOT IN ('P');

UPDATE EXT_RECEPTION.CF_RECEPTION_TYPE SET APPL_TYP = 'ПТ' WHERE FILE_TYPE = 'P';