--liquibase formatted sql

--changeset ggeorgiev:19.1
DROP VIEW [EXT_JOURNAL].[VW_JOURNAL];

--changeset ggeorgiev:19.2
CREATE VIEW EXT_JOURNAL.VW_JOURNAL AS
SELECT
	j.CODE,
	LEFT(j.code, 4)												as YEAR,
	SUBSTRING(j.code, 5, LEN(j.code))							as BULETIN,
	n.NODE_DEF_NBR												as SECT,
	nd.NAME														as SECT_DEF,
	COALESCE (e.ACTION_PROC_TYPE, e.ACTIONUDOC_PROC_TYPE)		as PROC_TYP,
	COALESCE (e.ACTION_PROC_NBR,  e.ACTIONUDOC_PROC_NBR)		as PROC_NBR,
	COALESCE (e.ACTION_ACTION_NBR,  e.ACTIONUDOC_ACTION_NBR)	as ACTION_NBR
FROM EXT_JOURNAL.JOURNAL_ELEMENT e
         JOIN EXT_JOURNAL.JOURNAL j on e.JOURNAL_NBR = j.JOURNAL_NBR
         JOIN EXT_JOURNAL.JOURNAL_STRUCT_NODE n on e.JOURNAL_STRUCT_NODE_NBR = n.NODE_NBR
		 JOIN [ipasprod].[EXT_JOURNAL].[NODE_DEFINITION] nd on nd.NODE_DEF_NBR = n.NODE_DEF_NBR
;

