--liquibase formatted sql

--changeset ggeorgiev:311.1

INSERT INTO EXT_CORE.CF_STATUS
(PROC_TYP, STATUS_CODE, ACCEPT_PAYMENT, ACCEPT_ANNUITY_PAYMENT, ACCEPT_ANNUITY_PAYMENT_WITHOUT_DATE_PAYMENT_CHECKS)
select s.PROC_TYP,s.STATUS_CODE, 0, 0, 0 from IPASPROD.CF_STATUS s
left join EXT_CORE.CF_STATUS es on es.PROC_TYP = s.PROC_TYP and es.STATUS_CODE = s.STATUS_CODE
join ipasprod.CF_PROCESS_RESULT_TYPE r on s.PROCESS_RESULT_TYP = r.PROCESS_RESULT_TYP
where es.STATUS_CODE is null and r.PROCESS_RESULT_TYP in ('W', 'L')


--changeset ggeorgiev:311.2
UPDATE e
SET e.ACCEPT_PAYMENT = 0
FROM EXT_CORE.CF_STATUS e
JOIN  IPASPROD.CF_STATUS s on e.PROC_TYP = s.PROC_TYP and e.STATUS_CODE = s.STATUS_CODE
join ipasprod.CF_PROCESS_RESULT_TYPE r on s.PROCESS_RESULT_TYP = r.PROCESS_RESULT_TYP
where r.PROCESS_RESULT_TYP in ('W', 'L')

