--liquibase formatted sql

--changeset mmihova:308.1
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_CHANGE_MARK_OWNER DEFAULT 'N' FOR CHANGE_MARK_OWNER;
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_CHANGE_MARK_REPRESENTATIVE DEFAULT 'N' FOR CHANGE_MARK_REPRESENTATIVE;
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_CHANGE_MARK_RENEWAL_EXPIRATION_DATE DEFAULT 'N' FOR CHANGE_MARK_RENEWAL_EXPIRATION_DATE;
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_INSERT_MARK_ACTION_PROTECTION_SURRENDER DEFAULT 'N' FOR INSERT_MARK_ACTION_PROTECTION_SURRENDER;
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_INSERT_MARK_ACTION_CANCELLATION DEFAULT 'N' FOR INSERT_MARK_ACTION_CANCELLATION;
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK DEFAULT 'N' FOR INSERT_MARK_ACTION_NON_RENEWAL_OF_TRADEMARK;
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD CONSTRAINT DF_INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY DEFAULT 'N' FOR INSERT_MARK_ACTION_NON_RENEWAL_OF_CONTRACTING_PARTY;

--changeset mmihova:308.2
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD INTERNATIONAL_REGISTRATION varchar(1) DEFAULT 'N';
ALTER TABLE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG ADD GENERATE_USERDOC_TYPE varchar(7);

--changeset mmihova:308.3
UPDATE EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG SET INTERNATIONAL_REGISTRATION = 'N';

--changeset mmihova:308.4
INSERT INTO EXT_CORE.CF_INTERNATIONAL_USERDOC_TYPE_CONFIG
(USERDOC_TYP, INTERNATIONAL_REGISTRATION, GENERATE_USERDOC_TYPE)
VALUES('ЗМР', 'S', 'ЗМРНОТ');