--liquibase formatted sql

--changeset dveizov:52.1
alter table EXT_CORE.CF_USERDOC_PERSON_ROLE
    add IND_TAKE_FROM_OWNER character varying(1) default NULL;

UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET IND_TAKE_FROM_OWNER = 'S' WHERE ROLE = 'GRANTOR';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET IND_TAKE_FROM_OWNER = 'S' WHERE ROLE = 'PAYER';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET IND_TAKE_FROM_OWNER = 'S' WHERE ROLE = 'PLEDGER';


