--liquibase formatted sql

--changeset dveizov:95.1
alter table EXT_CORE.CF_USERDOC_PERSON_ROLE
    add NAME varchar(255)
;

alter table EXT_CORE.CF_USERDOC_PERSON_ROLE
    add NAME_EN varchar(255)
;

--changeset dveizov:95.2
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Подател', NAME_EN = 'Applicant' WHERE ROLE = 'APPLICANT';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Заложен кредитор', NAME_EN = 'Payee' WHERE ROLE = 'PAYEE';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Длъжник', NAME_EN = 'Payer' WHERE ROLE = 'PAYER';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Лицензополучател', NAME_EN = 'Grantee' WHERE ROLE = 'GRANTEE';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Лицензодател', NAME_EN = 'Grantor' WHERE ROLE = 'GRANTOR';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Залогодател', NAME_EN = 'Pledger' WHERE ROLE = 'PLEDGER';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Стар притежател', NAME_EN = 'Old owner' WHERE ROLE = 'OLD_OWNER';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Нов притежател', NAME_EN = 'New owner' WHERE ROLE = 'NEW_OWNER';
UPDATE EXT_CORE.CF_USERDOC_PERSON_ROLE SET NAME = 'Представител', NAME_EN = 'Representative' WHERE ROLE = 'REPRESENTATIVE';

